### ISSUE TITLE
Problem activating plugin in local environment

### ISSUE THREAD

**Issue by anatrino** [tainacan/tainacan#1]
After following this guide: https://github.com/tainacan/tainacan/blob/master/docs/setup-local.md , when I go to my local environment and activate the Tainacan plugin, the following errors appear in my panel:

 ![tainacan](https://user-images.githubusercontent.com/8321285/35443047-bae55092-0290-11e8-8a94-ba025f1e5359.png)

**Comment by leogermani** [comment]
Hi Ana,

We are still in very early stages of development, keep this in mind.

For some reason this does not happen in our environments, but @jacsonp is making some changes in some parts of the code related to it right now, so hopefully it will get fixed with his next commits later on

**Comment by leogermani** [comment]
@anatrino could you give it a try now? Please use the develop branch now, we are starting to use gitflow.
