### ISSUE TITLE
Metadatum with spaces on title broke some exposers

### ISSUE THREAD

**Issue by jacsonp** [tainacan/tainacan#108]
When testing #81, checking URLs data, some items exposer is not parsing, debugging we discover that if the metadatum has space chars, some parsers not It support that value on key position

**Comment by jacsonp** [comment]
empty values plus space, broke some exposers too

**Comment by leogermani** [comment]
Remember metadata also have a slug. Maybe its juet the case of use the slug instead. Im not sure whether it is a best pratice of metadata standard to use sanitized names for the fields
