### ISSUE TITLE
Modal for Checkbox and Radio

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#122]
Create a modal with search and pagination for Metadata input on Item Edition Form that has long lists of Chackbox or radio.

**Comment by leogermani** [comment]
The modal works great.

But, similiar to what happen with the filter, the selected values should appear in the page even if they are not present in the first values that are displayed by default... The user must have somehow a feedback to see what values are selected outside the modal

maybe a solution like the filter, that always include selected values in the list

or dsiplay the values in some other way...

**Comment by leogermani** [comment]
Ok!

One final little bug.

When you are in the modal, with a list of RADIO buttons and go to the "Selected" tab, the button to remove the term does not work.

Also, fix the layout of the tabs
