### ISSUE TITLE
Gutenberg Blocks

### ISSUE THREAD

**Issue by Weryques** [tainacan/tainacan#136]
1 Gutenberg Blocks
- [x] 1.1 Collections carousel block
- [x] 1.2 Items grid block

**Comment by Weryques** [comment]
Updates

- [ ] 1.1 Collections carousel block
  - [ ] 1.1.1 Fixes non-interaction in save mode
  - [ ] 1.1.2 Fixes responsivity in edition mode

- [ ] 1.2 Items grid block
  - [ ] 1.2.1 Create css classes for generic styles
  - [ ] 1.2.2 Create options to choose among different image sizes
  - [ ] 1.2.3 Evaluate the possibility of use masonry

**Comment by mateuswetah** [comment]
I'm closing this issue as we'll break it into more specific issues related to the gutenberg blocks with a new tag for it.
