### ISSUE TITLE
Capabilities in Wordpress multisite

### ISSUE THREAD

**Issue by Weryques** [tainacan/tainacan#137]
When Tainacan is activated in network level of a Wordpress multisite, some capabilities are not created or available for users, like 'edit_tainacan-collections', impeding users to create new collections. But if Tainacan is activated at site/blog level, it's work perfectly.

**Comment by leogermani** [comment]
One solution is described here:

https://wordpress.stackexchange.com/questions/181141/how-to-run-an-activation-function-when-plugin-is-network-activated-on-multisite

BUT

I think we could just move this callback to our migration class and it should be fine
