### ISSUE TITLE
Improvements in CSV importer

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#138]
- [x] Create new special column to set the item status

- [x] Create new special column to inform the item ID (add options in the settings form to choose the action when a repeated item is found: update or ignore)

- [x] add the ability to add hierarchical terms in taxonomy metadata. The value can have ">>" indicating the hierarchical relation of terms. For example: "Rock >> Progressive Rock"

- [x] In the mapper (and this goes for all importers) add the option to "Create new metadatum" instead of having to create it manually. Bur for the CSV importer, lets define some conventions that users can put in the header so that tainacan will know what type of metadatum it should create.. Lets discuss this further

For example: Subject|textarea|required would inform that the column "Subject" is to be imported into a new metadatum called Subject, its type should be textarea and it should be required...

have to think what to do with taxonomy type, because there should be a way to infor what taxonoy to use or to create a new taxonomy as wel...

**Comment by vnmedeiros** [comment]
I did two commits covering the ability to add hierarchical terms in taxonomy metadata, 
for when the metadata using taxonomies allow multiple values:
https://github.com/tainacan/tainacan/commit/07ad04d99c790835f0f8e8bfa718f763b6392d3c
https://github.com/tainacan/tainacan/commit/6527b6c942b86ef695f5dfc22967aff41f09d14e

**Comment by eduardohumberto** [comment]
if the option "Create Metadatum" is selected, Tainacan will try to create a metadatum using the column header, the properties of this metadatum could be set by some conventions. 

Ex:
Subject|textarea|required|multiple 

This case would inform that the column "Subject" is to be imported into a new metadatum called Subject, its type should be textarea, it should be required and it should be multiple. if only the name is at the header the metadata type will be Text.

**Comment by leogermani** [comment]
special headers to handle item IDs and status are:

special_item_id and special_item_status

**Comment by leogermani** [comment]
Couple of things:

- [ ] Apparently you must always inform that the metadata is required if you want it to be multiple... 

importer should accept any case:
 Subject|textarea|required|multiple
 Subject|textarea|multiple
 Subject|textarea|required

- [ ] Add option to allow to choose the metadata to be private

- [ ] Intelligence to create metadata should be in the Importer Class, and not in the API endpoint

**Comment by leogermani** [comment]
Also, Ive got an error trying to use it. 

"Cant use type INT as object in class-tainacan-rest-importer-controller.php line 211"

**Comment by eduardohumberto** [comment]
the options to allow the metadata be private/public are:
 example|display_yes
 example|display_no
 example|display_never

**Comment by leogermani** [comment]
metadata to be private was to set the status of the metadata, not the visibility (but visibility is good, keep it!)

status can be private or public

**Comment by eduardohumberto** [comment]
the options to change the metadata status are:
example|status_public
example|status_private

**Comment by leogermani** [comment]
Did not work very well.. Some metadata were not created. And column special_item_status did not work. Ill send you the CSV Im using to test

**Comment by leogermani** [comment]
Setting item ID with special_item_id also did not work:

```
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function Tainacan\\Importer\\CSV::set_option(), 1 passed in /home/leo/devel/wp/wp-content/plugins/tainacan/importer/class-tainacan-csv.php on line 522 and exactly 2 expected in /home/leo/devel/wp/wp-content/plugins/tainacan/importer/class-tainacan-csv.php:22\nStack trace:\n#0 /home/leo/devel/wp/wp-content/plugins/tainacan/importer/class-tainacan-csv.php(522): Tainacan\\Importer\\CSV->set_option('item_id_index')\n#1 /home/leo/devel/wp/wp-content/plugins/tainacan/importer/class-tainacan-csv.php(125): Tainacan\\Importer\\CSV->handle_item_id(Array)\n#2 /home/leo/devel/wp/wp-content/plugins/tainacan/importer/class-tainacan-importer.php(690): Tainacan\\Importer\\CSV->process_item(0, Array)\n#3 /home/leo/devel/wp/wp-content/plugins/tainacan/importer/class-tainacan-importer.php(885): Tainacan\\Importer\\Importer->process_collections()\n#4 /home/leo/devel/wp/wp-content/plugins/tainacan/importer/class-tainacan-bg-importer.php(25): Tainacan\\Importer\\Importer->run()\n#5 /home/leo/devel/wp in /home/leo/devel/wp/wp-content/plugins/tainacan/importer/class-tainacan-csv.php on line 22, referer: http://localhost/wp/wp-admin/admin-ajax.php?action=tnc-bg_import&nonce=90b67268d5
```

**Comment by eduardohumberto** [comment]
the options to set a metadata as collection key:

example|collection_key_yes
example|collection_key_no

**Comment by eduardohumberto** [comment]
Couple of things:

- [ ]  Retrieve previously mapping used in the collection
