### ISSUE TITLE
In plugin screen, the WordPress logo / shortcut to control panel could be at left side. 

### ISSUE THREAD

**Issue by johanpdr** [tainacan/tainacan#141]
![position wp logo](https://user-images.githubusercontent.com/6567563/47521619-e7fbba80-d869-11e8-81cc-42ea2d465ca3.jpg)

**Comment by mateuswetah** [comment]
So far the design team does not agree with the proposal. The ideia is that the Wordpress button there is at the same position of "close" buttons in other screens. Besides that, alongside of Tainacan's logo, there will soon exist a "home" icon, which will lead to the yet-to-be-implemented home of the plugin.
