### ISSUE TITLE
Values in select box metadata comes with wrong a comma

### ISSUE THREAD

**Issue by johanpdr** [tainacan/tainacan#149]
A single value selected in a select box metadata type comes with wrong comma at his finish
![metadata value with comma](https://user-images.githubusercontent.com/6567563/47786838-c8daae00-dceb-11e8-964c-52f668c92c96.jpg)

**Comment by leogermani** [comment]
I can not reproduce it.

Can you give detailed instructions on how to reproduce?

**Comment by johanpdr** [comment]
Create some values in an selectbox metadata. 
Sending an item, select just one of these values in this selectbox metadata.
At finish, this single value come with this unnecessary comma

**Comment by leogermani** [comment]
Cant reproduce it... works fine for me in all cases

**Comment by leogermani** [comment]
Found this error in a multiple text metadata, not selectbox. Fixed
