### ISSUE TITLE
User metadata

### ISSUE THREAD

**Issue by johanpdr** [tainacan/tainacan#151]
Create a new metadata type that the users of installation is the value. The result is a screen similar of terms of taxonomies, but with the user informations and all of his itens attributed on repository.

**Comment by leogermani** [comment]
There is already this information and it is just a matter of creating the template in the theme. However there could be an issue to create a metadata type of "user", to be used in any way we want, and not just to identify the authors.

**Comment by leogermani** [comment]
Created #154
