### ISSUE TITLE
New metadata type: user

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#154]
Create a new metadata type called user. That shows as options a list of users in WordPress.

Have to discuss what options this could have (list all users? only users of a certain role? ...)

**Comment by johanpdr** [comment]
Just a new way to view / propose this: can we  forget the metadata dimension and absorb the WordPress users like a pre-created taxonomy type?

**Comment by mateuswetah** [comment]
This issue was addressed on recent commits for https://github.com/tainacan/tainacan/issues/354 (**release Beta 0.16**) release without us even remembering it's existence. New requirements such as the roles discussed here might be moved to a new issue.
