### ISSUE TITLE
Problema com a busca de itens para metadados de relacionamento

### ISSUE THREAD

**Issue by guitavs** [tainacan/tainacan#156]
Olá, 

Recentemente, identifiquei um problema ao tentar fazer o relacionamento entre coleções. Estou fazendo de maneira manual, visto que essa funcionalidade ainda não está disponível via importação CSV. Assim, criei uma coleção com os dados que quero relacionar em uma coleção, porém ao tentar buscar o dado, o campo de busca está limitado aos 10 últimos registros feitos na coleção (cujo os dados serão utilizados). Portanto, não consigo inserir do topo da lista, por exemplo. Como medida paliativa, fiz a inserção de 10 itens por vez, fazendo seus devidos relacionamentos. Entretanto, preciso utilizar esses dados em outra coleção. Por isso, gostaria de verificar a respeito. Desde já, muito obrigado.

A instalação que me refiro é a: https://medialab.ufg.br/ria/

**Comment by mateuswetah** [comment]
Olá Guilherme! Obrigado por reportar o erro, demorou um pouco mas encontramos a origem do problema aqui. Vai ser atualizado na próxima versão e então pediremos pra vocês validarem ;)
