### ISSUE TITLE
When the item title is too long, he isnt appears at collections items list

### ISSUE THREAD

**Issue by johanpdr** [tainacan/tainacan#157]
![2018-11-12 2](https://user-images.githubusercontent.com/6567563/48368087-de5fb880-e699-11e8-88aa-16da7a8b61e7.png)
![2018-11-12 3](https://user-images.githubusercontent.com/6567563/48368088-de5fb880-e699-11e8-9b97-bccb8e315e1d.png)

**Comment by leogermani** [comment]
You have to make them visible in "displayed metadata" options on the top of the table
