### ISSUE TITLE
Plugin Design Review

### ISSUE THREAD

**Issue by marcelolabrito** [tainacan/tainacan#164]
These are the points to be reviewed on the Plugin's interface

- [x] **Menu**
    - [x] Breadcrumb is too large when the collection or item's name is big 

- [x] **Add/Edit single Item** 
    - [x] Position of the Status Label (should be on the left side)
    - [x] Edit document and edit miniature - button is not completely rounded (should be a circle)
    - [x] Back button on the title - It's too big on the edit page
    - [x] Attachments - the right color is _grey 1_ 

- [x] **Bulk Add Items**
    - [x] The upload area hover's color is wrong (check on interactions' document)
    - [x] Position of the Status Label (should be on the left side)
    - [x] Back button on the title - It's too big on the edit page

- [x] **Add/edit Collections**
    - [x] Edit Images - button is not completely rounded (should be a circle)
    - [x] Title - Line should be _blue 3_

- [x] **Metadata (repository level)**
    - [x] When selected, the color of the title should be _blue 3_ (it's turquoise)

- [x] **Taxonomies** 
    - [x] Line below "new taxonomy" shouldn't go til the end of the area (one column free) 
    - [x] Arrow in "taxonomies by page" should be _blue 3_
    - [x] Title of the tabs should be _black_
    - [ ] There should be a checkbox next to the amount of children terms
    - [ ] There's no more images for the terms
  
- [x] **Importers**
    - [x] Select arrows should be _blue 3_

- [x] **Advanced Search**
    - [x] "close" arrow should be before the title's line ends (in the menu's dropdown)
    - [x] results - Search options' buttons should be in other position (check design file)
    - [x] Select arrows should be _blue 3_

- [ ] **Collections' list**
    - [x] Title of the tabs should be _black_
    - [ ] On trash, the options for each collection should be delete forever and restore it.

**Comment by mateuswetah** [comment]
Thanks for the feedback. I'm closing this issue now with the following observations:

- Checkbox on Terms page is part of a major issue that we'll need to face in the future, [this one](https://github.com/tainacan/tainacan/issues/73) here.
- For now, we're keeping image on term's form as some museums are using it as a temporally solution for the lack of the "expositions" concept that we've been discussing.
- I'm creating a separate issue for the "delete-restore" detail of the collections list. We'll get to it soon.

Feel free to reopen it or create a new one to discuss any other adjustments.
