### ISSUE TITLE
allow comments and star ratings for items #enhancement

### ISSUE THREAD

**Issue by fireiceviper** [tainacan/tainacan#170]
Most museum collections have mislabeled items and attributions, an easy way to correct this would be to let logged in users (logins could come from word press or possible other database with integration) comment on items and give them a rating (obviously not all users, but a start would be to make accounts for industry professionals)

**Comment by mateuswetah** [comment]
Hi there,
Comments are already available on Item's single page. All you have to do is check the "**Allow comments**" switch, right bellow the Thumbnail on Item Edition Page. 
Star ratings is something that was actually planned in the first designs of Tainacan, but we agreed that it could be a very specific demand, besides questionable. Not every digital repository would benefit of it and it could depend on definitions of "quality" or "preference" that are debatable. In any case, we believe we can provide such integration with other WordPress Plugins that already offer this feature. We just don't have any examples yet to test.
I'm closing this issue, but I invite you to discuss or propose these sort of features sending to our mailing list: tainacan@lists.riseup.net.
There, other people besides me can give opinion. I'm particularly interested in the concept of collaboration that you are bringing here. The whole idea of visitors warning wrong labeling is something with a lot of potential. 

Thanks anyways ;)
