### ISSUE TITLE
Create a plugin dependencies check page in the admin

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#174]

**Comment by leogermani** [comment]
Reference: https://github.com/WordPress/health-check/tree/8bf830011c03d09f44f5cbff446d4b86656a0605/src/includes

Check for

* WP version
* PHP version
* DB version 
* GD, imagick
* zip

check 
* max script runtime
* mpm ?

**Comment by leogermani** [comment]
test for permalink settings and .htaccess

**Comment by mateuswetah** [comment]
Inform if csv file upload is ok. Show maximum file upload.

**Comment by leogermani** [comment]
branch feature/system-check
