### ISSUE TITLE
New Block: Items Grid (static) 

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#187]
Item's grid manually selected 
Options:
- Source (collection or terms-list?)
- With and without titles;
- Size (3 options, maybe?)

Design example:
![captura de tela de 2019-02-01 14-27-20](https://user-images.githubusercontent.com/1184874/52135721-8f3c7a80-262d-11e9-92f9-ae7568dc0d7c.png)

**Comment by leogermani** [comment]
when trying to select items from a second collection (first was fine), I got

`Error trying to fetch items: TypeError: modalItems.push is not a function`
