### ISSUE TITLE
New Block: Items carousel (static)

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#191]
A item's carousel, displaying in one line with slider options. Items should be pick from react's modal.
Options:
- Source (from collection or term's list..?)
- Automatically slide items;
- Show or not item's titles;
- Arrows aside (simular to Funarte)

For rendering this on front-end of the post, we could consider using the same plugin that the theme currently uses for the attachments on item's single page.

Design preview (they say they will probably work more on this):
![image](https://user-images.githubusercontent.com/1184874/52137118-fad41700-2630-11e9-9fff-44027a822e4e.png)

**Comment by leogermani** [comment]
If you have more than one carroussel in the same page, clicking in the arrow in one carroussel almo moves all the others

**Comment by mateuswetah** [comment]
> If you have more than one carroussel in the same page, clicking in the arrow in one carroussel almo moves all the others

This should be easy to fix but apparently there is an issue when dealing with separate Vue instances... I opened the issue on the component repository, let's see how it goes...
https://github.com/surmon-china/vue-awesome-swiper/issues/537

**Comment by mateuswetah** [comment]
For this first version, we decided to release the block without allowing to have more than one per page/post. This is a option already existing for Gutenberg's "supports" array, so it will be easy to change in the future once we solve this.
