### ISSUE TITLE
Bug in Date metadata type

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#194]
Date metadatype is displaying incorrect dates in the visualization page at the admin area. It always shows current date instead of the actual saved date.

Hint: I think this component is trying to format the date to apply the date format configured in the WordPress admin panel. Recently we improved the backend of this component and now the `value_as_html` attribute of the metadata already handles it. I beleieve you should remove this behavior from the component.

**Comment by mateuswetah** [comment]
It's not happening on my...
![image](https://user-images.githubusercontent.com/1184874/52139256-c3686900-2636-11e9-9ea9-e415f66f15ad.png)
In any case, on item's visualization page at admin, we render date using the `.date_i18n` value returned from API. Should I use `.value_as_html` then?
