### ISSUE TITLE
Can't set collections archive page as home

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#197]
Reported by @johanpdr:

If one wishes to make the collection archive page (`/collections`, `/colecoes`) the website home page, it looks like there is no easy way to do that. 

The desired interaction would be to select it on the _customizer_ section responsible for setting home page, but the page is not listed there.

**Comment by leogermani** [comment]
There is a new issue to discuss this #338 

There is no easy way to do that, WordPress don't give us a good way to change that and it would be difficult to do this work with every theme.

The best solution is the user to create a new page, use the Gutenberg block to list collections, and set this page ans the front page.
