### ISSUE TITLE
Better link detection on metadata text input

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#198]
Reported by @johanpdr:

When editing a text metadata, if you insert URLs starting with `www` it works fine, but other valid links (such as those with only `http://`) won't be understood as link and will render as plain text. Is it possible to make this better?

**Comment by leogermani** [comment]
If you type only `www.abc.com`, without the `http://`, the link is created but misses the `http` prefix, creating a broken link.

`http://` must be automatically added in these cases
