### ISSUE TITLE
Temporarly disable bulk edition

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#199]
When collections are too big, bulk edit actions may break MySQL. We will refactor this and make bulk edit work in steps...

Meanwhile, lets hide the option to bulk edit too many items by removing the option to "Select all XYZ items in all pages", and allowing bulk edition only to the items visible on each page.

**Comment by leogermani** [comment]
So here is what has been decided:

- [ ] Remove the option to  "Select all XYZ items in all pages"
- [ ] Display this option only when a constant is present in `wp-config.php`

**Comment by mateuswetah** [comment]
Can you create that constant so I can hide the option? That's really easy to do. Maybe we should merge the branch with the admin check page first, then add the constant.
