### ISSUE TITLE
Initializing repositories on API classes must use singleton

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#2]
example:

```
public function init_objects() {
		$this->items_repository = new Repositories\Items();
		$this->item = new Entities\Item();
		$this->item_metadata = new Repositories\Item_Metadata();
		$this->collections_repository = new Repositories\Collections();
	}
```

You should use global objects or implement a singleton Trait for all classes

**Comment by Weryques** [comment]
Pensando no conceito de singleton. No sentido de transformar a classe em um espaço único e restrito,  que só se permite transações seriais, não é bom pro caso um API em que eu preciso de respostas rápida a requisições.
Eu sugiro, usarmos as classes globais que já existem.

**Comment by leogermani** [comment]
done
