### ISSUE TITLE
Refactor Bulk edition

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#200]
Change bulk edition feature to work in steps, avoiding slow and heavy queries to break MySQL.

**Comment by jacsonp** [comment]
maybe using background processing to large editions, creating a notification on panel to user that a bulk edition is in progress, and lock posts to edition until is ready.

**Comment by leogermani** [comment]
There are some problems with this approach:

1. It breaks the usability. Today you can perform several actions in the same set of selected items. This is important, because you may want to do something that needs 2 or 3 steps to accomplish and you dont want do lose the items you selected (specially because the change made in the first step may change the results of the filters you've chose if you search for items again). If we do background processing.. you will have to leave and wait for the process to complete...

2. If a background processing is running and you are allowed to browse and edit the collection while its running you could have unintended consequences... We probably would have to "lock" the collection while the process is running... and this would be a pain...

What Im thinking is to do something that requires the user to wait and keep the browser open, and not beeing able to do anything else while waiting. So one request to the api would process a couple of hundred of items, return, and another requests would be performed... till the end, with a progress bar and some feedback.

After an action is complete, the user still can perform other actions in the same set of items, as it is today...

The default number of items affected in each request will be something conservative, that will work in most hosts, but that can be changed by a contant in wp-config

**Comment by mateuswetah** [comment]
Once we dive into this, there is something we could look into the vue compoent:

- [ ] Get rid of the weird random key logic that is passed to taxqueries nowadays from inside the component.

Much had been done in order to allow page refreshing and search queries rebuilding but maybe not all of it remains necessary. We don't need to render terms anymore, for example, as the taxonomy advanced features is now a text search instead of a tag input.

**Comment by vnmedeiros** [comment]
To do:
- [ ] implement the main functions of bulk editing
- [ ] improve messages for the generic bg process
- [ ] create the notification bar of current bulk edit runs
- [ ] enable actions to be performed on the same set of items already selected
- [ ] improve bulk edit execution interfaceasd
- [ ] simplify the use of classes: `Generic_Process_Handler`, `Background_Generic_Process`, `Background_Process` and `Generic_Process`

**Comment by leogermani** [comment]
- [ ] write tests

**Comment by leogermani** [comment]
- [ ] refactor sequence. It should not rely on bulk edit group
- [ ] check Bulk add and see what can be kept and what has to be disabled...

**Comment by leogermani** [comment]
About the Bul ADD workflow:

- [ ] When new items are added, we will add a group metadata right away, so we can bulk edit them right after the add process is finished.
- [ ] The bulk edit button will open the Bulk edit modal (and not the page we currently open). This will give better feedback to the user that the editions are not applied immediately.
- [ ] Sequence edit stays at is. It can be the first step right after items are added or can be performed after triggering the bulk edit actions
- [ ] We will add to the output information of the Bulk edit background processes a link to Sequence Edit (and bulk edit?) the items.
