### ISSUE TITLE
Exporter breadcrumb should display exporter name, not slug

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#207]
See attached image

**Comment by leogermani** [comment]
![Captura de tela de 2019-02-28 17-26-53.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5385ea5febef97b1f959fde8/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2723dd5b165ed1a3b5058424caa5c5d5c56e0ebc969f9ec6923ce4e01ffd43f5f71c03816ade9d41fbb57be208b4ed3beba881dc2bc2f39f5c9de116a415841c3aa1f27aa8b4ac052f74ee44c56ac163261ef71377555d9.png)

**Comment by mateuswetah** [comment]
Same is happening with importers... I should load the list and pass the appropriate name according to the slug.
