### ISSUE TITLE
OAI PMH Importer

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#209]
- [x] Add option to "Import Sets as collections" (as it is now) or "Import Sets as a taxonomy"

Check the results of a test impor we did in

https://tainacan.medialab.ufg.br/

from http://rubi.casaruibarbosa.gov.br/oai/request

**Comment by leogermani** [comment]
In the test mentioned above, only 100 Sets were imported. There are more. I believe pagination is missing in this step.

**Comment by leogermani** [comment]
- [ ] handle sources without Sets (create a default name for the collection if necessary)

**Comment by eduardohumberto** [comment]
- [ ]  handle sources without completeListSize attribute
