### ISSUE TITLE
Allow user to right click and open items in new tab in the admin

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#212]

**Comment by mateuswetah** [comment]
With been through this before, the problem is that for that we should use `href` attributes on item. This was possible on theme's list but on admin we need to handle more stuff, so the click is treated by a click event:
```javascript
onClickItem($event, item, index) {
            // Handles multiple selection with CTRL key
            if ($event.ctrlKey || $event.shiftKey) {
                this.$set(this.selectedItems, index, !this.selectedItems[index]);
            } else {
                // Prevents opening item when is on trash, explains why.
                if(this.isOnTrash){
                    this.$toast.open({
                        duration: 3000,
                        message: this.$i18n.get('info_warning_remove_from_trash_first'),
                        position: 'is-bottom',
                        type: 'is-warning'
                    });
                // Actually changes page.
                } else {
                    this.$router.push(this.$routerHelper.getItemPath(item.collection_id, item.id));
                }
            }
        },
```

I'm not sure of a solution to that, but I'll look out.

**Comment by mateuswetah** [comment]
Ok, just found a common used solution here: I can detect the right click and then create my own "Open link on new tab" popup. It's pretty much what Google Drive does.

**Comment by mateuswetah** [comment]
Ok, just found a common used solution here: I can detect the right click and then create my own "Open link on new tab" popup. It's pretty much what Google Drive does.
