### ISSUE TITLE
Change the "Mass Actions" warnings from the Trash tab

### ISSUE THREAD

**Issue by johanpdr** [tainacan/tainacan#214]
Remove from Trash could be changed to "Restore Item" in the "Mass Actions"

![image](https://user-images.githubusercontent.com/6567563/54544871-3cb9e200-497f-11e9-93f2-a067a514e17a.png)

**Comment by mateuswetah** [comment]
In English, the string is "Recover from trash" so really the translation should be done as "Recuperar da lixeira". I would agree on changing it to "Restore from trash" maybe...
