### ISSUE TITLE
Bug when use taxonomie's as a filter

### ISSUE THREAD

**Issue by Braaga** [tainacan/tainacan#235]
In an especific collection, I can't use my taxonomy as a filter. 

All the configurations about it apparently is correct.

Link to a youtube video explain this: https://youtu.be/ITV4ktquP9E

**Comment by mateuswetah** [comment]
Hi @Braaga; Your collection seems fine, I can't figure out clearly what is happening... let's discuss this in detail on our mailing list: https://lists.riseup.net/www/info/tainacan
In case it's identified as a bug, we'll keep this issue. We might give you instructions there on how to inspect the requests to identify the problem.

**Comment by leogermani** [comment]
@Braaga 

I believe this was fixed and released in version 0.9. It had to do with facets endpoint not handling well hierarchical taxonomies.

https://tainacan.org/blog/2019/05/20/tainacan-beta-0-9-elastic-search-bloco-de-busca-de-itens-e-novos-importadores/

I'm closing this issue. Feel free to open it again if it is not fixed.

Leo,,
