### ISSUE TITLE
More clear sorting options select

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#240]
After some discussion with the design team, we agreed on removing the "toggle" order buttons and replace it by a select. The reason for that is because it is not clear whether the buttons aesthetics is representing the current state of the list or what the button is capable of doing. Icons can be confusing and are not enough to tell this story. It is hard to find examples of this on similar UI because we have many "OrderBy" options. In fact, on an old version of Atom, they used two selects:
<img width="945" alt="browse-archdesc" src="https://user-images.githubusercontent.com/1184874/58031667-3b2fa600-7af7-11e9-8bbe-da881f2fa784.png">

**Comment by leogermani** [comment]
Is there still room to discuss the icons?

In my opinion it is cleared if we change the order of the lines and keep the arrows always going down. My point is that you always read the list from the top to bottom, the items change their order, you dont change the way you read them...

Something like this drawing:

![arrows](https://user-images.githubusercontent.com/971483/59416404-ad647500-8d9b-11e9-9f8f-6e2fcb1ef43d.png)

**Comment by mateuswetah** [comment]
@leogermani hahahah nooooo

In terms of iconography, the arrows have more strength in our head than the bars. I agree that the ambiguity still exists in both cases, and would remain if we changed. That's why the labels are there now, to end this doubt in case it appears. Please, pleaaase close this xD
