### ISSUE TITLE
New Numeric Filter (single value instead of range)

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#242]
Range filter is confusing when dealing with only one value, we should have one filter for that.

**Comment by leogermani** [comment]
Not sure if there is a solution but in my laptop the filters break in 2 lines. image below:

![Captura de tela de 2019-06-24 05-47-27](https://user-images.githubusercontent.com/971483/60004781-9ea37b00-9643-11e9-8f2b-bc60483f8457.png)

**Comment by mateuswetah** [comment]
Yeah it's ugly... I could find a solution where instead of only occupying this minimum width, the select expands to the maximum. We just can't avoid the break itself, it is necessary because the date field contains a dropdown with the date picker that requires a minimum width.
