### ISSUE TITLE
enable to order items by metadata

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#25]

**Comment by leogermani** [comment]
Investigate how to deal with empty metadata value

**Comment by leogermani** [comment]
Not sure if this is going to happen. 

Apparently it would require a big change in the SQL WP_Query generates and we dont want to do that.

Or we accept the fact that items without that metadata disappear from the list.

References:

https://wordpress.stackexchange.com/questions/55263/order-posts-by-custom-field-and-if-custom-field-is-empty-return-remaining-posts

https://stackoverflow.com/questions/53714365/sql-ordering-results-from-joined-table

**Comment by mateuswetah** [comment]
Let's warm this up a bit. After discussing, we agreed that it would be acceptable to have the list returning a warning or notice that "the current sorting shows less items than the total of the list". This would happen when the items are ordered by metadata that are not filled in every item. So let's see if this would work.

**Comment by leogermani** [comment]
Confirmed that no change in the back end is necessary. The API already supports it.

Simply pass `orderby=meta_value` or `orderby=meta_value_num` (see WP_Query reference to know the difference) and an additional `metakey` parameter indicating which metadata to use.

example:

`...&orderby=meta_value&metakey=2345&order=ASC`

**Comment by leogermani** [comment]
It is working. Now we have to inform the user that items that do not have a value for the metadata are excluded from the list.

@mateuswetah could you discuss this with he design team? Ive talked to them and the first answer was to use the Alert modal. But I think this is not enough, it would be good to leave some sort of information on the top of the list reminding the user there is a filter applied.

Also, today is hard to tell what is used to order the list, because the select never shows it. It could be improved

**Comment by leogermani** [comment]
when you get out of a collection and enter another one, the "sorting" dropdown keeps showing the value selected in the last collection you visited
![Captura de tela de 2019-03-18 17-58-15.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5385ea5febef97b1f959fde8/125516c66e82c728ace21e0d46cb958a379791a8cfedba03b058fc95694222337b54f2723dd5b065ee1a3b5058424ba45c595a56e0ebc969f9ec6923ce4e01ffd43f5f71c03816ade9d41fbb57be208b4ed3beba881dc2bc2f39f5c9de116a415841c3aa1f27aa8b49c952f74ee44f5ca0113362e370357555d9.png)

**Comment by mateuswetah** [comment]
The error mentioned above should be solved now.
