### ISSUE TITLE
Feature: Duplicate Items

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#250]
Offer items duplication on item's list.

**Comment by mateuswetah** [comment]
It seems that we might do the duplication server side via API.

**Comment by leogermani** [comment]
Added endpoint, example:

`POST -> .../collection/123/items/23/duplicate`

It will return the new created item.

Just not sure how you will handle the errors. There are 2 possibles errors

1. a complete error, will return 400 code if the item is not found, the user dont have permission, or other fatal error

2. a partial error. Imagine there is an item with many metadata, but an error happens only in one metadata. This value is not saved but the item is created. (for example, if there is a `collection_key` metadata). I have this error but I'm not sure how to return it... and if it should be returned.

**Comment by mateuswetah** [comment]
Commit [72388e](https://github.com/tainacan/tainacan/commit/72388ecd143e156b6331c3edbf32109782c14449) shall attend most of this.

**Comment by leogermani** [comment]
Added `copies` and `status` parameters to the endpoint.

* Copies - allows you to ask fore more copies of the item, and not just one. (default 1)
* status - allows you to set the statuses of the new items. Note that the item must validate to have the status set. If it doesn't validate it will be kept as draft. (default draft)

The return format was changed. Now created items are returned as an array inside `items` index (same format as get_items)

**Comment by leogermani** [comment]
Updating here that we have discussed and came up with the idea that this feature will have a behavior similar to the "bulk add items"

When you click to create copies of an item, you will be redirected to a page where you can edit the "template", once you are finish, you can choose the number of copies and then create all the items and sequence edit them. (or just go back to the list)

**Comment by leogermani** [comment]
329418a8aeb93e8df5435725182fb9a367c592c5
