### ISSUE TITLE
Show Documents of attachments list (admin)

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#252]
Instead of only showing thumbnails, preview attachments on admin using a modal with the embeded content.

**Comment by mateuswetah** [comment]
This is actually half working already. It shows the `file.description.redered` in a modal. This works fine for html5 video, audio and any image. The latest commit is a workaround for PDF files: it renders their content inside an iframe. I'm not sure this is the best way, but solves for now. We should discuss what else we can render here, otherwise it will appear as a link to the file.

**Comment by mateuswetah** [comment]
We should also include here the option to render in the item form the description of the media file, that can be edited on WordPress media modal. We should also be able to render this description from item's API on thumbnail requests, so it can be used for better accessibility.

**Comment by leogermani** [comment]
Let's:

1. See if it is possible to add one more element to the native `media` WP API Endpoint, adding something like `tainacan_rendered` to the `media.description` object
2. Create a function `get_attachment_as_html()` that the theme can use
3. See how the lightbox used in the theme can display a HTML content
