### ISSUE TITLE
generate pdf files of the items both individually and too of result of a search

### ISSUE THREAD

**Issue by vnmedeiros** [tainacan/tainacan#258]
generate pdf files of the items both individually and too of result of a search
for example:
- generate PDF for specific collection items
- generate PDF for items that uses a taxonomy

**Comment by leogermani** [comment]
This is a plugin that implements a new Exposer

**Comment by leogermani** [comment]
Plugin released, still need some work to publish in the WP repository (localization, for example).

https://github.com/tainacan/wp-plugin-tainacan-pdf-generate

Also, this plugin could also offer a PDF Exporter.
