### ISSUE TITLE
Review Logs

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#261]
Logs are being created but we didnt give much attention to them yet.

For 1.0 we have to make sure they are properly created, stored and displayed to the user

**Comment by leogermani** [comment]
- [ ] review permissions check (bind can_read to items and collections permissions)

**Comment by leogermani** [comment]
- [ ] Add a note to Log titles when Log was created during an import
- [ ] Verify if and why importers are publishing private items when updating items
- [ ] Remove or change the behavior of the Trash icon in the attachments list. It is not deleting the attachment, but only detaching it from the item. This does not create a log
- [ ] Review the behavior of the "Send to trash" button on the item page. Apparently, it is not sending a DELETE request, but rather sending a PATCH changing the status.
- [ ] Handle Logs in the old format in the api response

**Comment by mateuswetah** [comment]
While implementing admin side, some issues were noticed:

- [ ] After updates on translatable labels, I can't identify updates that are corresponding to metadata and filters sorting updates. My suggestion is to treat them as separate actions, which is the way that I've been using to handle different logs display;
- [ ] Also, one of the labels is ` Ordination metadata`, is that correct?
- [ ] If I set a document of type PDF" the `old_value` and `new_value` will return me the Document, which is the ID here, but not the Document Type.
- [ ] In one of my tests, after setting a document of type PDF, the response from the logs API included not only a `item` object , with the related object, but a `items` with the same content!

**Comment by mateuswetah** [comment]
One extra thing:

- [ ] Keep legacy logs working;

**Comment by leogermani** [comment]
- [ ] add links to all related objects (item, metadata, collection, etc...)

**Comment by leogermani** [comment]
- [ ] fix css for search and date filter

**Comment by mateuswetah** [comment]
Apparently,

- [ ] Filter updates on repository level are not setting log title or description

They also return `collection_id` as `filter_in_repository`, whereas in repository metadata this goes as `default`. It would be good to set a standard. This detail seems to be treated all over the admin code actually, many cases of OR handling the situation.

So far, there is no direct way to achieve Taxonomy Id on a Term update, as the `object.taxonomy` brings only something like `tnc_tax_133188`. If it is bad to handle this on frontend then we need to

- [ ] Return taxonomy_id on related object when updating a term.

**Comment by mateuswetah** [comment]
Return `creation_date` values formatted nicely as in Collection's end
point :)
