### ISSUE TITLE
Add CONTAINS option to search by taxonomy in advanced search

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#267]
This issue depends on #266

Now that we can search items based on a search in terms, we can add this option in the advanced search. Currently, advanced search offers an auto-complete where you have to select term by term to perform a search for items. With this change, users will be able to use any string to search items that have terms that contain this text in the name.

**Comment by mateuswetah** [comment]
After https://github.com/tainacan/tainacan/commit/e5d34f065e635e3a1d475d6e74d2ae2ee9a1f0c9, advanced search should be working with a simple text input instead of autocomplete.
