### ISSUE TITLE
Avoid error when Imagick is misconfigured

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#271]
After some security updates, Imagick library comes configured in a way that does not allow it to open PDF files.

This prevents Tainacan from creating thumbnails from PDFs covers. But actually, the application breaks and the user gets no feedback.

This issue is to avoid the application to break in those cases. Simply dont create the thumbnail and carry on.

Also, if possible, add this note to the System check page

**Comment by leogermani** [comment]
Reference: https://alexvanderbist.com/posts/2018/fixing-imagick-error-unauthorized

**Comment by vnmedeiros** [comment]
for Imagick to work the depedence **ghostscript** is required.
