### ISSUE TITLE
Roles and permission configuration interface

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#274]
Create an interface to configure roles and permissions.

We are going to discuss the details on this issue, but the general idea is to have a way to configure what each role can do in each collection and also to be able to grant permissions to roles or specific users.

**Comment by mateuswetah** [comment]
The roles management on the administrative panel is something to discuss... It looks like there are so many plugins for WordPress that already do this, that it could be repetitive to create a session only for Tainacan... 

![Screenshot_2019-07-08 Edit Role ‹ Tainacan Teste — WordPress](https://user-images.githubusercontent.com/1184874/60821625-4d82a380-a17a-11e9-95e9-3d3b799621d7.png)

**Comment by leogermani** [comment]
Yes, but the thing is that these interfaces are really hard to use. The capabilites names are difficult to understand, and our capabilities will be even worse. Think of "edit_tnc_col_12_items" for example...

We need something easier to understand and that, sometimes, might actually mean adding or removing several capabilities at once (as it is now to add moderators)

**Comment by mateuswetah** [comment]
Ok I see it... Our interface could provide specifics such as entities filtering (collection, taxonomy, item...). It just seems to me that we can't provide them much better information as we don't have a description of the capabilities coming from API. Maybe if we follow certain conventions we can link to the Wiki like this:
https://wordpress.org/support/article/roles-and-capabilities/#manage_network

**Comment by leogermani** [comment]
How to check for permissions on the front end?

- [ ] add schema to API responses
- [ ] add _links to API responses
- [ ] add actions to _links API responses

References:
https://core.trac.wordpress.org/ticket/44287
https://developer.wordpress.org/rest-api/extending-the-rest-api/schema/
