### ISSUE TITLE
Better warning for sorting effects on item's list.

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#278]
The tooltip aside the number of item's on list is not enough to indicate that custom metadata sorting may be causing the list to have less items. We should indicate this more clearer.

**Comment by leogermani** [comment]
https://github.com/tainacan/tainacan/commit/dbeac4f798858cefb5571ff4b2dbf5fc3a19cb1a

**Comment by leogermani** [comment]
It looks good to me.

I think we should remove the option to dismiss this warning, and leave it there always. 

It would be nice to have a different behavior when the list brings no items. Maybe a different message and a different placeholder that says "no items were created in this collection".

could be "no items found, only items with XXX are been displayed. perhaps order by something else?"

**Comment by mateuswetah** [comment]
I agree with the label change for empty list. I don't agree with removing the option to dismiss although. This is not like what happens to the modal, where it actually never appears again. If a user enters the item's list again, it will be there. So it is already annoyingly "on the face".

**Comment by leogermani** [comment]
Ok, but now you have to leave the list and come back to it to see the warning again.

If you change the order to sort by another metadatum, the warning should re-appear

**Comment by mateuswetah** [comment]
Agreed!

**Comment by leogermani** [comment]
When no items are found, I think we should not have this "no item created in this collection - add new"

![Captura de tela de 2019-07-31 14-42-59](https://user-images.githubusercontent.com/971483/62234317-d7501600-b3a0-11e9-9a6e-fc91383bbb10.png)

**Comment by mateuswetah** [comment]
> When no items are found, I think we should not have this "no item created in this collection - add new"

@leogermani, this separation is made today by checking ithe value returned by `X-WP-Total`, then instead of  showing this message, this is shown:

![image](https://user-images.githubusercontent.com/1184874/62235481-71b15900-b3a3-11e9-8fdb-f43e0a0483f4.png)

I use it to differentiate situations where no results exist from situations where the list is actually empty.

**Comment by leogermani** [comment]
But did you see my screenshot?

I think the difference is because I dont have any filters applied

**Comment by mateuswetah** [comment]
I see... I'm just thinking how would I safely differentiate this two states...

**Comment by mateuswetah** [comment]
Check latest commit (https://github.com/tainacan/tainacan/commit/00ec44a2be09672c86e367bc5ee93f32bedf1c81).
