### ISSUE TITLE
"save and create other" on taxonomy page

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#281]
Give the user an option to save and create another taxonomy, as we do with items

**Comment by leogermani** [comment]
It is working but there is an useless request. 

when you go to the new taxonomy page, there is a request to an undefined taxonomy

`http://localhost/wp-json/tainacan/v2/taxonomy/undefined/terms?hideempty=0&order=asc&parent=0&offset=0&number=100`

and right after it, there is a request with the correct ID.

Is it possible to avoid it?

**Comment by mateuswetah** [comment]
Uhmm, possibly yes, I'll check it!
