### ISSUE TITLE
Display full hierarchy for taxonomy metadata

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#283]
When displaying the value for a taxonomy metadata, display the whole tree, and not just the seleced term, in a breadcrumb format:

Musical Instruments > Percussion > Tamborim

**Comment by mateuswetah** [comment]
I'm wondering how would this go for an item that has many terms, being most of them from the same parent... Won't it make it too polluted? Shouldn't we display this only in a tooltip or in something collapsable?

**Comment by leogermani** [comment]
I think we should give it a try and see how it goes in the real world

**Comment by leogermani** [comment]
![Captura de tela de 2019-07-29 16-16-12](https://user-images.githubusercontent.com/971483/62075459-7ba85000-b21b-11e9-907f-483498d23b89.png)

**Comment by mateuswetah** [comment]
Do they have a `<span>` tag around with a class so that a theme can customize the way we did with the separators?

**Comment by leogermani** [comment]
No, will add it. What you suggest?

- [ ] add a HTML element with a class in the separator

Also, I will add a filter so the CSV exporter writes the same format the importer accepts, which uses ">>"

- [ ] add a filter to change the separator and make CSV exporter use it

**Comment by mateuswetah** [comment]
Great! 
Well, we used `multivalue-separator` for the previous, so maybe `hierarchy-indicator`?
