### ISSUE TITLE
Offer URLs modal on Item Page

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#288]
Add the Exposers Modal (Alternative URLs) to the item single page.

**Comment by leogermani** [comment]
what about item pages on the theme side?

**Comment by mateuswetah** [comment]
> what about item pages on the theme side?

It has always been there, no?

**Comment by leogermani** [comment]
There is not this offer on item single page on the theme for now. This will be addressed later, on the theme.
