### ISSUE TITLE
Document visibility control

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#291]
Add an option to control document and attachments visibility control.

They can be set to public or private and will make determine if the document itself and the items attachments should be displayed to the regular public even if the item is public.

For now public and private is enough. For the future we may add more options, such as whether download is allowed or not, or to make low resolution versions available and lock only high res.

**Comment by ssastrodev** [comment]
Hi Tainacan Dev Team!

Thanks for working super hard on this plugin and the regular updates, we have been using it and are very happy with how it works :)
May I kindly ask how the Document visibility issue is going? I see it has been moved to Backlog, which I assume is owing to the large number of requests you are receiving for urgent matters, which is totally understandable.

Thanks again!

**Comment by mateuswetah** [comment]
Hey, we're glad that you are enjoying the plugin!

As a matter of fact, this issue had landed a bit low on the priorities (we have a board to decide our workflow: https://github.com/orgs/tainacan/projects/1). I would say that the next three major releases will be focusing on:

- Improve Relationship and Taxonomy metadata features;
- Allow the configuration of metadata sections;
- Improve our mapping options to allow further integration between different repositories;
- Create a plugin dashboard to offer new places to se new settings that might arrive once we release 1.0;

Regarding the document visibility, it remains by now sync with the Item visibility. While we have instructions for protecting the files of private items (check [this](https://tainacan.github.io/tainacan-wiki/#/pt-br/optimization?id=blindando-o-wordpress) if you haven't), it is a challenge to come up with a decent strategy for protecting the files in public items. We have another idea that is being discussed, to implement "file" metadata types, which would allow easier control of the visibility, but that is pretty draft by now.

Hope you understand the pace and be assure that we won't look away of this issue, the time will arrive for us to face it!

**Comment by ssastrodev** [comment]
Many thanks @mateuswetah for the detailed reply, and explaining the challenges. It is very much appreciated. We totally understand and look forward to future releases!

**Comment by mateuswetah** [comment]
After some discussion, we agreed that the Document visibility will always be tied to the item visibility. It's concept is in fact something we want to relate as "the item itself". However, the issue for having private files attached to public items is a big one and we aim to solve it using the [Attachment Metadata type](https://github.com/tainacan/tainacan/issues/665), which is planned for 2025.
