### ISSUE TITLE
Not importing a .csv file that contains only `special_`

### ISSUE THREAD

**Issue by vnmedeiros** [tainacan/tainacan#299]
**Bug description**

When importing a .csv file that contains only `special_` columns the values of items are no modifies, and on log _erro showed theses errors mensagens:
```
failed on item 0
failed on item 1
failed on item 2
```
This erro in this case, is caused because is not created a mapper of metadatum with the collumns of .csv file.

**Comment by vnmedeiros** [comment]
https://github.com/tainacan/tainacan/commit/5ecf858bd60a2f530f738ba59614ef15fd8a6c4c

**Comment by leogermani** [comment]
This is working now, but we should fix the interface. When there is no metadata to be mapped, the screen is a bit broken.

We could do one of these:
- just fix it a bit with a message that there is no metadata
- add a message saying that there is no metadata but informing that there are special fields
- skip this screen
