### ISSUE TITLE
Issues with Terms Endpoint

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#310]
Two issues that I found lately:
- [x] The `postin` parameter not working;
- [x] When passing ` fetch_only=name,url,header_image` the `url` always return `null`.

**Comment by vnmedeiros** [comment]
the parameter `postin` not exist for term in WP, an alternative is use the parameter added `include`, but that parameter not working on way describe in documentation, his behavior is likely to change, a ticket has been opened about its use:
https://core.trac.wordpress.org/ticket/48284#ticket
