### ISSUE TITLE
Filter and Advanced Search Results different

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#318]
We have a situation on this installation: https://mhn.tainacan.org/. The following two requests to the `https://mhn.tainacan.org/wp-json/tainacan/v2/collection/233012/items` endpoint with this parameters:

```
context=edit
perpage=12
paged=1
order=DESC
orderby=date
admin_view_mode=table
fetch_only=thumbnail
fetch_only_meta=280706,233016
taxquery[0][taxonomy]=tnc_tax_232911
taxquery[0][operator]=LIKE
taxquery[0][originalMeta]=232953-tnc_tax_232911-term
taxquery[0][taxonomy_id]=232911
taxquery[0][isFetching]=0
taxquery[0][terms]=kleuber
advancedSearch=true
```
and 
```
context=edit
fromBreadcrumb=true
perpage=12
paged=1
order=DESC
orderby=date
admin_view_mode=table
fetch_only=thumbnail
fetch_only_meta=280706,233016
taxquery[0][taxonomy]=tnc_tax_232911
taxquery[0][terms][0]=7372
taxquery[0][compare]=IN
```
are returning different values. The first one shows an empty list and the second displays some items. I am not sure what could be causing the error so far, need to investigate...

**Comment by vnmedeiros** [comment]
@mateuswetah, the index on arguments array tax_query don't  mounted correctly by the front-end, but this is not a critical problem.

**Comment by mateuswetah** [comment]
@vnmedeiros I'll be opening a separate issue for that if is not high priority.

**Comment by leogermani** [comment]
Apparently, the problem was that WordPress was not properly updating terms count because its default behavior is to count only when related posts have the `publish` status. We changed that
