### ISSUE TITLE
Make taxonomy metadata multiple by default

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#326]
This was a request from the people working on museums. The taxonomy could by default, accept multiple values. I'm not sure if we should do it this way, though.

**Comment by leogermani** [comment]
This is not simple to accomplish right now and requires some work. We can do it if it has a higher priority than other issues, or wait a bit if it's just something desirable

**Comment by mateuswetah** [comment]
After years working with this, I'm closing in favor of keeping the current behavior. Yes Taxonomies tend to me useful when multivalued but that is certainly not a rule and I've seen a lot of situations where single-valued was the choice. Besides that, if we go that way, it may be a behavior unclear that affects only one type of metadata, when we have so many other types... It does not hold up in my idea.
