### ISSUE TITLE
Better handling multiple metadata associated to the same taxonomy.

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#327]
As far as I know, it is not possible to have two taxonomy metadata on the same collection, associated with the same taxonomy. Or it actually is possible, but causes a lot of inconsistencies, like having one term inserted in one field and also appearing on the other... If that is the case, we should have a way to avoid or alert this, right into the metadata creation routine.

**Comment by leogermani** [comment]
We already validate metadata upon save so you can't have two taxonomy metas using the same taxonomy in the same collection.

I think we should also validate:

- [ ] If there is a taxonomy meta inherited by parent collection or repository
- [ ] If there is a taxonomy meta down in a child collection
