### ISSUE TITLE
Importer: Avoid items with same date

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#336]
Sometimes items are created too fast in the importer and end up with exactly the same Date and time.

As a result, when ordering posts by date, sometimes they come in a random order, because they have identical dates.

Its a good idea to make importers always assure posts are created with different dates, adding one or few seconds to the date when necessary. This would avoid this problems

See also #337

**Comment by mateuswetah** [comment]
The problem that this could cause is solved when issue #337 is solved. Thus we don't see an issue with having items with the same date (as long as it in fact was created ate the same moment).
