### ISSUE TITLE
Support for themes

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#338]
Currently, the only way users can use the faceted search in third party themes is using a shortcode.

We have to think of better ways to integrate tainacan features in any theme. Things such:

. configuring a collection, or the list of collections, as the Home Page
. configuring a template for the collections page without the need of a shortcode
. have a gutenberg block to add the faceted search?

This issue is to discuss this and implement it

**Comment by mateuswetah** [comment]
Some theme support related issues were opened: #345 , #346 and #347 . The last one may help with a future Gutenberg block for faceted search, I'm not sure...
