### ISSUE TITLE
option to turn off activity logs

### ISSUE THREAD

**Issue by vnmedeiros** [tainacan/tainacan#382]
add an option to be turn off activity logs during import.

**Comment by leogermani** [comment]
This option already exists:

https://github.com/tainacan/tainacan/blob/86af70d8a4757c44d5e66171b668983bd11b47f2/src/classes/repositories/class-tainacan-repository.php#L37

Here's an example of it being called during CSV Import:

https://github.com/tainacan/tainacan/blob/86af70d8a4757c44d5e66171b668983bd11b47f2/src/classes/importer/class-tainacan-csv.php#L638

**Comment by leogermani** [comment]
so today, in theory, it only create one activity log when the item is created, but don't create individual logs for each metadata of the inserted item

**Comment by vnmedeiros** [comment]
At this point, logs are disabled only if it is an update of item?
https://github.com/tainacan/tainacan/blob/86af70d8a4757c44d5e66171b668983bd11b47f2/src/classes/importer/class-tainacan-csv.php#L638


and for new items? there would be no need to disable here either e.g:
https://github.com/tainacan/tainacan/blob/86af70d8a4757c44d5e66171b668983bd11b47f2/src/classes/importer/class-tainacan-csv.php#L641

**Comment by leogermani** [comment]
it seems code on line 638 might be in the wrong place. Look at the comment on 637...

**Comment by vnmedeiros** [comment]
aaah of course...
maybe the correct thing is to leave the logs active for `updates` and disabled for the `inserts`

**Comment by leogermani** [comment]
yes, in the insert leave only logs for `Items`, which is only one activity per item
