### ISSUE TITLE
CSS interferindo no estilo geral do site

### ISSUE THREAD

**Issue by alexlana** [tainacan/tainacan#390]
Olá! A versão 0.16 está interferindo no CSS global. Por exemplo, os links do site ficaram com a cor verde do Tainacan e os espaçamentos dos menus mudaram.

**Comment by mateuswetah** [comment]
Oi @alexlana, valeu pelo aviso. Eu tentei reproduzir aqui mas não consegui. Testei com o tema TwentyTwenty e outros pra ver se os links estavam diferentes... mas nem no site nem no painel admin notei alguma diferença. Pode nos mandar um link ou pelo menos algumas capturas de tela pra tentarmos reproduzir?

**Comment by alexlana** [comment]
Posso colocar online até amanhã se ajudar. Nas imagens em anexo:

- no texto, o link deveria ser laranja
- no menu, deveria ter um espaço maior em cima e embaixo
- a imagem do css é onde achei a interferência da cor do link. A do menu eu não encontrei aqui agora...
![Captura de Tela 2020-05-19 às 19 49 28](https://user-images.githubusercontent.com/4108621/82386392-ac57b100-9a0a-11ea-8374-0392c3dd3bba.png)
![Captura de Tela 2020-05-19 às 19 49 35](https://user-images.githubusercontent.com/4108621/82386397-ae217480-9a0a-11ea-92d2-8dead12709b1.png)
![Captura de Tela 2020-05-19 às 19 51 30](https://user-images.githubusercontent.com/4108621/82386400-afeb3800-9a0a-11ea-875f-0da5b14188f2.png)

**Comment by alexlana** [comment]
ah... acho q pode ser q interfira só em temas q usem o bootstrap.

**Comment by mateuswetah** [comment]
Uhmm, se rolar o link vai ajudar sim. Estou tentando entender pq aconteceria isso. Os estilos do admin só são carregados (ou pelo menos só deveriam ser) na página do admin do Tainacan. Tem exceções como na lista de itens dentro do tema, mas neste caso estariam no escopo da classe dela. Qual o nome do tema? Vou tentar instalar aqui.

**Comment by alexlana** [comment]
fiz em cima desse: https://br.wordpress.org/themes/simple-bootstrap/

mas a gente mudou pro bootstrap 4 e mexeu em várias coisas. vou subir até amanhã de manhã e posto o link aqui. vou testar sem login como administrador tb, q estava logado hoje

**Comment by mateuswetah** [comment]
Beleza, fico no aguardo. Testei aqui com o Simple Bootstrap e na folha de estilos não chegou a cor dos links do tainacan (pelo menos não em uma página de post). A única cor do link está vindo do `_reboots.scss` q pertence ao próprio tema.

**Comment by alexlana** [comment]
Está online: https://fc.tmp.br/casb/casb/contribua/

A senha: senha4acesso

Tem várias coisas do Tainacan carregando no site. Se não estiver acontecendo em outras instalações, vou ver o q posso ter feito errado...

**Comment by mateuswetah** [comment]
Obrigado pelo acesso, estou averiguando. Acho que podemos ver uma maneira de isolar melhor essas classes. Enquanto isso, para o seu caso, vc pode setar a variável:

```css
:root {
    --tainacan-secondary: #f36f20;
}
#tainacan-admin-app {
    --tainacan-secondary: var(--tainacan-turquoise5, #298596);
}
```

**Comment by alexlana** [comment]
Massa! Valeu pela indicação! A ideia é tentar usar para o inventário do CAsB, vou tentar fazer "kits" de telescópio + lentes + tripe + etc, e ver se consigo colocar um sistema de empréstimos vinculado ao Tainacan, onde as pessoas possam falar do estado de conservação tb. Não estudei bem ainda o plugin pra ver se já tem essas coisas ou se eu faria um plugin extra :)

Vou estudar esse material! Valeu!

**Comment by mateuswetah** [comment]
Hhhaha sensacional. Quando estiver público ou se precisar de ajuda, pode nos chamar lá na lista.

Agora voltando à _issue_, deu pano pra manga aqui. O problema é que temos um js que é carregado, que renderiza a lista de itens (seja em páginas do item, seja em um bloco gutenberg). Este js é um bundle de `vuejs`, onde internamente rolam vários `@imports` de `.scss `que contém nosso estilo. 

No geral, podemos resolver essa situação limitando nossas declarações dento do escopo do painel administrativo do Tainacan, das Lista de Itens e de modais (que são adicionados ao `body,` fora da `div` da lista). O problema dos links que você comentou, vai ser mais tranquilo resolver desta maneira, como acabei de fazer neste _commit:_ https://github.com/tainacan/tainacan/commit/df3ed0b71cdf2c2431a97906b513296543a4f1ea#diff-616c3e69254e3ce5db28991bb13e8936

Então deve estar ok pra próxima versão... mas isso não vai resolver o problema todo... alguns dos `@imports`  que fazemos são do código da [Buefy](https://buefy.org), a biblioteca de componentes Vue que usamos, que por trás tbm usa a [Bulma](bulma.io/), uma framework de css. Eles não tem prática de identificar as classes deles com letras pré-fixadas (como _b-row_), o que faz com que eventualmente alguns temas usando outras frameworks css tenham estes problemas (o espaçamento errado nos menus provavelmente vem daí).

Tamo discutindo isso com eles faz um tempo e eu abri uma _issue_ tbm, mas não acho q vai ter uma solução muito rápida no horizonte:
https://github.com/buefy/buefy/issues/2497

Infelizmente, pra casos como o seu o que podemos fazer é tentar identificar algumas classes que podemos colocar dentro do escopo (como rolou agora com os links) e quando não, sugerir criar css de maior prioridade para consertar as coisas.

**Comment by mateuswetah** [comment]
Só pra deixar isto aqui atualizado... depois de muito conversar com o pessoal da Buefy, eles entendem que isto não vai ser feito na framework deles, mas estão com um projeto extra, irmão da Buefy e que provavelmente vai resolver esta questão; https://oruga.io/. Então a solução provavelmente vai passar por migrarmos para ele no momento em que estiver mais maduro. Estou acompanhando o projeto de perto pra ver quando podemos fazer isso.

**Comment by mateuswetah** [comment]
Uma atualização aqui:

Embora estejamos longe de migrarmos para a Oruga ainda (dado ao status em desenvolvimento do projeto), nas últimas versões adotamos algumas estratégias de lazy-loading dos nossos JS e CSS que devem ajudar a isolar melhor as classes e reduzir estes conflitos. Se for possível fazer um teste com a 0.18.4 @alexlana para nos dizer se houve alguma melhora, ficamos gratos!

**Comment by mateuswetah** [comment]
Fechando já que não tivemos retorno. Caso alguém volte a topar com esta questão, pode abrir uma nova issue :)
