### ISSUE TITLE
Attachments uploaded to a private collection are not displayed correctly in the Tainacan GUI

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#398]
**Bug description**

Attachments uploaded to a private collection are not displayed correctly in the Tainacan GUI.

Private files are put in a folder prefixed with _x_ (as described in Issue #241) but the Tainacan media browser thinks they are in a regular folder without the _x_ prefix.

This might be because I use a separate subdomain for media? Maybe Tainacan tried to put a .htaccess file for redirecting (also as described in #241) but failed because of the separate subdomain?

**How to reproduce such bug**

Use the following template to create a step-by-step guide:
1. Go to an item in a private collection
2. Upload a new file attachment
3. The file is not displayed correctly

**Expected behavior**

The file should be displayed correctly to users with the appropriate permissions. Do I need to add my own .htaccess file on the media subdomain?

**Screenshots**
the attachment in the Tainacan GUI:
![Skärmavbild 2020-07-06 kl  14 38 39](https://user-images.githubusercontent.com/2394405/86593976-84aab100-bf96-11ea-9658-60144404ffe9.png)
the url as presented in the media library:
![Skärmavbild 2020-07-06 kl  14 20 28](https://user-images.githubusercontent.com/2394405/86593534-b707de80-bf95-11ea-8bef-148015d4c350.png)

actual path on the server (including _x_):
![Skärmavbild 2020-07-06 kl  14 34 06](https://user-images.githubusercontent.com/2394405/86593568-c71fbe00-bf95-11ea-8f0b-0e690465f150.png)

wordpress media settings:
![Skärmavbild 2020-07-06 kl  14 31 36](https://user-images.githubusercontent.com/2394405/86593537-b8390b80-bf95-11ea-8872-1b7183489d86.png)

**Comment by vnmedeiros** [comment]
Hi @Ambrosiani 
Recently has fixed an bug (https://github.com/tainacan/tainacan/commit/c3148daa911df1cadc52e00c5a73086ab74dd0a5) when accessing an item's private files. If there is a special character in the file name, a 404 response was generated.
 
In your case, does the file inside the _x_153 / 266 folder have any special characters? (ç, õ, ò, ó, â, ã, ...)

**Comment by Ambrosiani** [comment]
@vnmedeiros hi, no only ascii + underscore.

image url on server: https://media.ambrosiani.se/tainacan-items/_x_153/266/Aron_Ambrosiani.jpg
image url in Tainacan GUI: https://media.ambrosiani.se/tainacan-items/153/266/Aron_Ambrosiani.jpg

**Comment by vnmedeiros** [comment]
@Ambrosiani, I tried replicate the error locally, using the same file and did not get a 404 answer:
image folder path: `tainacan-items/_x_1300/1307`
![dd](https://user-images.githubusercontent.com/1179250/86623305-bc662880-bf97-11ea-88f5-317e0d083c8b.png)

some users related problem using image cache, are you using any caching tools?

**Comment by Ambrosiani** [comment]
@vnmedeiros yes, the media subdomain (where my files/attachments are stored) runs nginx. Details here: https://support.loopia.com/wiki/autobahn/

**Comment by vnmedeiros** [comment]
Hi @Ambrosiani 
Please try if this issue has been resolved in the last release?
