### ISSUE TITLE
No cutting of the title in faceted search

### ISSUE THREAD

**Issue by cutterkom** [tainacan/tainacan#425]
**Context and motivation**

Is it possible to prevent the title from being cut off after around 50 characters in the facet search? I would like the complete title to be displayed. 

I can't find an argument in the documentation of template tag (https://github.com/tainacan/tainacan/blob/develop/src/classes/theme-helper/template-tags.php) that takes care of that. 

Can you point me to a solution?

**Comment by mateuswetah** [comment]
Hi @cutterkom. This is probably something that should be handled via css by themes, or in different ways according to the view mode. But in order to point you to a solution, could you show me exactly where the title is being cut? Is it in the items list? Maybe a screenshot?

**Comment by cutterkom** [comment]
It's in the "Record" view. 
<img width="381" alt="grafik" src="https://user-images.githubusercontent.com/4574033/91718022-e51f2e80-eb92-11ea-8d42-cf339ce30633.png">

**Comment by mateuswetah** [comment]
Ok, this is the behavior of this view mode (records) and most of the others, actually. The cut limit is not defined by characters, but by container size, via css. The solution would requires the following css:

```css
.tainacan-records-container .tainacan-record .metadata-title p {
    white-space: normal;
}
```
Let me now if it works for you!

**Comment by cutterkom** [comment]
Thanks! 

I had to change it to
```
.tainacan-records-container .tainacan-record .metadata-title {
    white-space: normal !important;
}
```
to make it work.

**Comment by mateuswetah** [comment]
Great :)

We have plans for expanding the view modes API to allow adding options to them. So in the future we could have an option to visually disabling that. For now its a bit hacky but you can customize as you prefer via css ;)
