### ISSUE TITLE
Upload error when sending file to collection

### ISSUE THREAD

**Issue by lwdias** [tainacan/tainacan#433]
**Bug description**
When I upload a file (jpg, pdf, etc) to an item in any existing collection, the file does not open.
I realized that if I create a new collection and send the first item, the upload works, but from the second item the upload doesn't work anymore.
The first item (which opens) is sent to the folder .... /wp-content/uploads/sites/2/2020/10/itemname.jpg

from the second (which no longer opens), it sends to the folder ... /wp-content/uploads/sites/2/tainacan-items/32/43/itemname. jpg

I recently upgraded wordpress to 5.5.1, I don't know if this is the reason for the problem...

**How to reproduce such bug**

1. Open Tainacan admin panel (in Wordpress)
2. Select a created colection (that already has at least one item)
3. Click in Add new -> Add new item
4. Click in file (to upload a new file)
5. In the Wordpress Media Modal, send any type of file (jpg, pdf, etc)
6. Try to open the file just uploaded, the file will not open, as if it hadn't been sent

**Expected behavior**
The uploaded file should open.

**Desktop:**

 - OS: macOS Mojave 10.14.5
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)
 - Wordpress: 5.5.1
 - Tainacan: 0.16.3

**Comment by lwdias** [comment]
I recently upgraded wordpress to 5.5.1, I don't know if this is the reason for the problem

**Comment by leogermani** [comment]
Hi @lwdias ,

This is happening possibly due to permission configurations on your server. Maybe the apache user does not have permission to create the `tainacan-items` folder?

Can you see the folder and file created in the file system?
Does the file has more than 0 Bytes?

Also, since you are using Multi Site, Under Network Admin > Settings there are some restrictions (file size, file types, etc) that apply to each individual blog and might affect the upload in tainacan as well.

**Comment by lwdias** [comment]
I didn't find anything wrong in Network Admin > Settings....
The tainacan-items folder has all the permissions... 

The link of the image is /wp-content/uploads/sites/2/tainacan-items/32/43/itemname. jpg but the folder has this structure:
.../wp-content/uploads/sites/2/tainacan-items/32/_x_43
.../wp-content/uploads/sites/2/tainacan-items/32/_x_48
.../wp-content/uploads/sites/2/tainacan-items/32/_x_53

And inside the folder are files...

It seems that tainancan is pointing to the wrong url...

**Comment by leogermani** [comment]
By the structure of the folders, it seems that items 43, 48 and 53 are marked as private.

When a collection or an item is private, the attachments go to a folder with this `_x_` prefix. This will protect users without permission to view the items to view the attachments.

Details here: https://tainacan.github.io/tainacan-wiki/#/dev/private-files

As a logged in user with the right permissions, when accessing `https://.../wp-content/uploads/sites/2/tainacan-items/32/53/file.jpg`, you should get this file under the `_x_53` folder.

If this is not happening, there's something wrong and we would need to further debug it.

This magic happens here: https://github.com/tainacan/tainacan/blob/fbb6a98278d6a4458e6039033db896f6b286cb5a/src/classes/class-tainacan-private-files.php#L187

There is an open issue about large files not being properly served: https://github.com/tainacan/tainacan/issues/297

**Comment by lwdias** [comment]
yes, in fact the images are inside the folders with the prefix _x_. However, both the collection and the items are public. Whether I try to create a new item or edit an existing one, the files are being sent to the _x_ folders, even though the visibility of the collection and item are public.

**Comment by leogermani** [comment]
That's weird. Can you try saving one of these items as private and see if it works? And then as public again to see if it gets fixed?

@vnmedeiros I think this is something worth debugging to see what's going on.

**Comment by vnmedeiros** [comment]
Hi @lwdias 
recently had some problems when dealing with files with special characters in their names (-, ç, ~, ...), in your scenario do the files have some kind of special character?

**Comment by lwdias** [comment]
> That's weird. Can you try saving one of these items as private and see if it works? And then as public again to see if it gets fixed?
> 
> @vnmedeiros I think this is something worth debugging to see what's going on.

I created a new item, as private. But the image link was ... / wp-content / uploads / sites / 3 / tainacan-items / 9/1160 / ciencias_livro-scaled.jpg
If I try to access the link ... / wp-content / uploads / sites / 3 / tainacan-items / 9 / _x_1160 / ciencias_livro-scaled.jpg the image opens, but in tainacan, on the control panel, the image that the system tries to search is without the _x_

Saving the item as public, nothing has changed, the image remains only in the _x_ folder and the link without the _x_

**Comment by lwdias** [comment]
> Hi @lwdias
> recently had some problems when dealing with files with special characters in their names (-, ç, ~, ...), in your scenario do the files have some kind of special character?

No, they don't.

**Comment by vnmedeiros** [comment]
@lwdias  try create a item with same file, but rename this files removing the trace(hyphen) of filename: _ciencias_livro**-**scaled.jpg_. Just as a test

**Comment by lwdias** [comment]
I renamed it, but the error it occurs...

**Comment by lwdias** [comment]
In my testes here, it seems that the functions  get_post_status_object($item->get_collection()->get_status()) and get_post_status_object($item->get_status()) are returning public as false even for public collections and items... the file that I checked is /tainacan/classes/class-tainacan-private-files.php

**Comment by leogermani** [comment]
Are you using any other plugins? If so, can you share the list?

**Comment by lwdias** [comment]
- Contact Form 7
- Contact Form CFDB7
- Delete Delete Site
- Desativar Comentários
- More Privacy Options
- Multisite Plugin Manager
- Network Plugin Auditor
- SSH SFTP Updater Support
- WP Activity Log

**Comment by leogermani** [comment]
Thanks,

Would it be possible for you to test the upload while deactivating those plugins? Chances are there's a conflict between tainacan and one of these plugins and it would be much easier to address if we know which is it.

**Comment by mateuswetah** [comment]
@lwdias any news on this?

**Comment by mateuswetah** [comment]
Also closing this due to lack of feedback. There are also similar issues being discussed in our Discourse, which I believe is a better place for this: https://tainacan.discourse.group/
