### ISSUE TITLE
Items list breaks after advanced search

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#442]
**Bug description**

When you make an advanced search and go back to the normal items list, the list breaks

**How to reproduce such bug**

1. Go to Items List on the admin
2. Choose the "Records" display mode
3. Click on Advanced Search
4. Perform a search
5. Click on "Items" on the top level menu
6. Click on "Back" to go back to normal view
7. Change any filter

**Expected behavior**

The list should refresh with new filters

But what happens is that the items list is never updated (unless you change the view mode)

 - OS:Mac OS
 - Browser Firefox

**Comment by mateuswetah** [comment]
Hi @leogermani we couldn't reproduce this behavior, neither on the admin or public items list. Does it happens with any type and metadata (the one selected on the advanced search) and any filter?

**Comment by leogermani** [comment]
Before clicking on the Back button, click on the top level menu "Items". (updated the bug description)

**Comment by mateuswetah** [comment]
Possibly related to #321. We'll handle this in 0.19 release, as so far we couldn't not reproduce again.
