### ISSUE TITLE
Prevent HTML injection inside text inputs

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#447]
Prevent HTML injection within elements:
- [x] collection
- [x] metadata
- [x] documents
- [x] taxonomies
- [x] terms

**Comment by Ambrosiani** [comment]
a question about this – I'm currently using a regular text field to provide a CC license w link (see for instance the last field on https://monument.kvinnohistoriska.se/kvinnans-sak/appelmosvagga/), inputing regular html in the input field. How will this be handled in 0.18?

**Comment by vnmedeiros** [comment]
Hi @Ambrosiani 
We are thinking of leaving some tags released probably for cases like yours, but this is still under discussion.
Remembering that if you insert a link as plain text in a text-like metadata it should already generate as format link tag

**Comment by mateuswetah** [comment]
Yeah possibly we could offer this in a Markdown metadata type, to still allow links and basic formatting. This is in our roadmap for the next months
