### ISSUE TITLE
tainacan.org/api-docs is down

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#451]
**Bug description**

it seems https://tainacan.org/api-docs/ is down – returning a blank page and a console error (see screenshot):

<img width="1537" alt="Skärmavbild 2020-11-16 kl  09 34 02" src="https://user-images.githubusercontent.com/2394405/99229929-f4effb80-27ee-11eb-9700-32e2bde585d1.png">

**Comment by Ambrosiani** [comment]
(I guess this should be posted in another repo, sorry about that)

**Comment by mateuswetah** [comment]
Hi @Ambrosiani. 

We use a plugin for generating that doc, there should be some issue with the latest WP version... I'll check it, thanks for letting us know!

But yeah, I believe things like this would be better reported via our mailing list: https://lists.riseup.net/www/info/tainacan

So I'll close this for now and let you know once it is fixed!

**Comment by mateuswetah** [comment]
BTW @Ambrosiani. https://tainacan.org/api-docs/ is back on track!
