### ISSUE TITLE
Lots of API requests failing

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#452]
**Bug description**

I'm getting a bunch of 500 responses (the "critical failure" wordpress page) when trying to look at collection entries. It seems almost all Tainacan API requests are failing. List of collections () still works but except for that I haven't found any that still return data. Haven't been able to test extensively because of #451 

**How to reproduce such bug**

Not sure – everything was looking good last week. As far as I can tell I didn't change anything on the site. I have previously been doing manual cleaning inside the sql table so that is a probable cause of error.

**Screenshots**

<img width="1542" alt="Skärmavbild 2020-11-16 kl  09 29 07" src="https://user-images.githubusercontent.com/2394405/99229546-75622c80-27ee-11eb-95ab-65a969611931.png">

(running Wordpress 5.5.1).

**Comment by Ambrosiani** [comment]
php error thrown when trying to load a single item:

<img width="860" alt="Skärmavbild 2020-11-16 kl  13 17 51" src="https://user-images.githubusercontent.com/2394405/99251938-730fca80-280e-11eb-807e-415254a52a95.png">

**Comment by mateuswetah** [comment]
Hello again!

Last we week we accidentally released a testing version of the 0.17 release into the WP repo. We are extremely sorry for that! 
Although, I don't think it is the cause for any of these errors, as we haven't been able to reproduce something like this. In any case, I would suggest you to try this version, which was updated after some feedback of the Release Candidate:

[tainacan.zip](https://github.com/tainacan/tainacan/files/5546199/tainacan.zip)

We shall release the official version later today or tomorrow. It would be important to find out if this is really something related to the plugin! Please provide us some feedback ;)

**Comment by Ambrosiani** [comment]
hi, updating to the 0.17 RC solved this! The existing Tainacan was still at 0.16.3.

**Comment by Ambrosiani** [comment]
@mateuswetah thank you so much! looking forward to testing 0.17 more thoroughly :)

**Comment by mateuswetah** [comment]
Uhm... ok. If you have your plugin set to automatically update for newer versions, it might have been caused by updating to 0.17 (the accidental one that we uploaded) and then rolling back to 0.16.3. After that the site may have been lost looking for assets and endpoints of the future version. We are sorry for the inconvenience. Soon the official one will be out!

**Comment by Ambrosiani** [comment]
no, I don't have automatic updates enabled – very strange.
