### ISSUE TITLE
metadata error

### ISSUE THREAD

**Issue by lwdias** [tainacan/tainacan#454]
**Bug description**

I have the Tainacan plugin installed in a multisite wordpress installation. But in one of the websites, the items of any collection are not showing... when I open the browser console, there is a 500 internal server error in the url https://acervosvirtuais.ufpel.edu.br/acervodochorodepelotas/wp-json/tainacan/v2/collection/134/metadata/?nopaging=1

Opening this URL with the debug of wordpress activated, it shows the following error:

`Fatal error: Uncaught Error: Call to a member function _toArray() on null in /var/www/html/wp-content/plugins/tainacan/classes/api/endpoints/class-tainacan-rest-metadata-controller.php:310 Stack trace: #0 /var/www/html/wp-content/plugins/tainacan/classes/api/endpoints/class-tainacan-rest-metadata-controller.php(390): Tainacan\API\EndPoints\REST_Metadata_Controller->prepare_item_for_response(Object(Tainacan\Entities\Metadatum), Object(WP_REST_Request)) #1 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(1050): Tainacan\API\EndPoints\REST_Metadata_Controller->get_items(Object(WP_REST_Request)) #2 /var/www/html/wp-includes/rest-api/class-wp-rest-server.php(376): WP_REST_Server->dispatch(Object(WP_REST_Request)) #3 /var/www/html/wp-includes/rest-api.php(339): WP_REST_Server->serve_request('/tainacan/v2/co...') #4 /var/www/html/wp-includes/class-wp-hook.php(287): rest_api_loaded(Object(WP)) #5 /var/www/html/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #6 /var/www/html/wp-includes/plugin.php( in /var/www/html/wp-content/plugins/tainacan/classes/api/endpoints/class-tainacan-rest-metadata-controller.php on line 310
Há um erro crítico no seu site.`

I have no idea how to fix this... seems to be a problem with metadata

**How to reproduce such bug**

Use the following template to create a step-by-step guide:
1. Go to https://acervosvirtuais.ufpel.edu.br/acervodochorodepelotas/
2. Click on any collection, like the https://acervosvirtuais.ufpel.edu.br/acervodochorodepelotas/paulinho-martins/?view_mode=table&perpage=12
3. You can see, through the tainacan filter menu that the category has items in it, but they are not displayed

**Screenshots**
Screenshot of the problem in the collections: http://srv36.teste.website/~lwdias/error.png

**Versions**
Wordpress 5.1.3
Tainacan 0.16.2

**Comment by mateuswetah** [comment]
Hello again @lwdias!

Thanks for detailed description. Before we dive into the details to see if we can solve this, could you try to access the same content using the current Release Candidate? We shall release the version 0.17 today and it will be great to find and solve issues like this!

[tainacan.zip](https://github.com/tainacan/tainacan/files/5553733/tainacan.zip)

**Comment by lwdias** [comment]
the version 0.17 solved the issue.
Thank you so much!
