### ISSUE TITLE
add metadata ID as css class?

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#469]
https://github.com/tainacan/tainacan/blob/12820be07c6e9bbb3f2f3aa8bcf71da5ce6f0a21/src/classes/entities/class-tainacan-item.php#L533

hi, how do I add the metadata ID/slug as an additional css class for styling? I realize it's this line but I don't know what php variable to add…

basically for a metadata with id="license" I want to add the class "metadata-id-license" so I can add specific styling.

currently I've used the existing metadata-type classes but would like more flexibility. see https://monument.kvinnohistoriska.se/kvinnans-sak/komboloi-worry-beads/

**Comment by mateuswetah** [comment]
Hi @Ambrosiani. You're right, it would be some place around there. A few lines bellow the object `$metadatum_object` is instantiated and then we can access the ID via `$metadatum_object->get_id()`. Ideally, we should offer this option of displaying the metadata ID or class via some argument to this function:

https://github.com/tainacan/tainacan/blob/12820be07c6e9bbb3f2f3aa8bcf71da5ce6f0a21/src/classes/theme-helper/template-tags.php#L48

Which is the one called by themes when displaying the metadata list. I'll think on a solution for it after our year-end recess ;)

**Comment by mateuswetah** [comment]
Solved thanks to the pull request on 0.17.3!
