### ISSUE TITLE
Collections not appearing in form submission block

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#470]
**Bug description**

On my test site, collections appear in the "collection picker" of the form submission block. However on the production site, no collections appear.

test site:
![Skärmavbild 2020-12-21 kl  18 34 59](https://user-images.githubusercontent.com/2394405/102805462-8ab51280-43bb-11eb-9da9-49468e2fe6d1.png)

production site:
![Skärmavbild 2020-12-21 kl  18 35 21](https://user-images.githubusercontent.com/2394405/102805464-8b4da900-43bb-11eb-8ed2-a105d0c9035a.png)

**How to reproduce such bug**

Use the following template to create a step-by-step guide:

**Expected behavior**

I expected the collections to appear.

**Desktop (please complete the following information):**

both using latest Safari 14.0.2/macOS 11.1

both sites are using Tainacan 0.17.2, WordPress 5.6

The collections appear as expected in the API endpoint `/wp-json/tainacan/v2/collections` on both sites.

any idea where I should continue my troubleshooting?

**Comment by mateuswetah** [comment]
Uhmm my first guess would be that your collection on the production site is not enabled for items submission. Could you check that on your Collection settings?

**Comment by Ambrosiani** [comment]
ah of course 🤦‍♂️ thank you…
