### ISSUE TITLE
Dashboard Tainacan Reports:

### ISSUE THREAD

**Issue by mateuswetah** [tainacan/tainacan#483]
Splitting this into some phases:
- [x] Basic info (totals, percentage, etc);
- [x] Filters by entities (collection, user, etc);
- [ ] More complex info (combination of two different data, time series, etc);
- [ ] Gutenberg blocks for each chart;

**Comment by vnmedeiros** [comment]
First metrics:

Repository level:
- [ ] Total number of collections on repository
- [ ] Total number of items in the repository
- [ ] Number of items (private/public/draft/trash)

Collection level:
- [ ] Total number of items per collection
- [ ] Number of items (private/public/draft/trash)

**Comment by mateuswetah** [comment]
What we have ahead:

- [ ] Add zero values to activities date;
- [ ] Add chart for total of activities per user (stacked by activity type);
- [ ] Readjust space for metadata distribution;
- [ ] Add logarithmic scale to all columns charts;
- [ ] Get name and picture of users from the new reports api;
- [ ] Add hierarchy navigation to facets on the items per taxonomy in collection level;
