### ISSUE TITLE
generate uuid at post creation?

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#484]
**Context and motivation**

for permanent identifiers, uuids are a good thing to have.

**Ideal solution**

maybe generate a uuid v4 when creating a new Tainacan post? one implementation here: https://www.bjornjohansen.com/uuid-as-wordpress-guid

**Additional context**

We're going to use the unique, persistent ids when connecting our database to the Swedish aggregator SOCH (Swedish Open Cultural Heritage)

**Comment by mateuswetah** [comment]
Hi @Ambrosiani.

I'm sorry for taking so long to answer this, we were discussing the issue.

Although it is an interesting standard, we are understanding that it is not exactly a consensus in the many fields of digital archives that our project may be used for. That doesn't mean it wouldn't be nice to have it as an optional configuration. Is there anything that we could do to help you integrate this easily in your context without making it default for every user? Maybe we can discuss a plugin for that, and pull requests, as you know are always welcome!

**Comment by Ambrosiani** [comment]
hi, yes, a small dedicated plugin might be the best solution. I will experiment a bit following the suggested approach (change the guid at post creation) and report back :)

**Comment by mateuswetah** [comment]
I'm closing this in favor of #921. We're in a moment of reorganization of our priorities and this might be solved by an incoming Unique Identifier metadata.
