### ISSUE TITLE
Background processes stuck forever

### ISSUE THREAD

**Issue by cgrevisse** [tainacan/tainacan#513]
**Bug description**

Background processes for CSV export are queued but never executed (it states "Progress: There are no details about this process (0%)" respectively "Last processed on: Unknown date."). The necessary cron job `tnc-bg_exporter-cron` calling `Tainacan\Background_Exporter->handle_cron_healthcheck()` is executed every 5 minutes. Inside the logs, we get

```
BG_PROCESS: running handle_cron_healthcheck
BG_PROCESS: Checking if process tnc-bg_exporter is running:
BG_PROCESS: running handle_cron_healthcheck: dispatching
```

**How to reproduce such bug**

1. Use CSV export on a collection.
2. Under processes, the background process seems to be stuck.

**Expected behavior**

Should not be stuck but executed some time.

**Additional context**

`DISABLE_WP_CRON` is set to `true`. Tainacan version 0.17.4.

**Comment by vnmedeiros** [comment]
Problem resolved with commit: (https://github.com/tainacan/tainacan/commit/22d2cd57b308817566c82632c9276916b6ed7882). The process queue lock expiration time (**_queue_lock_time) was not being set, which resulted in an eternal wait.
