### ISSUE TITLE
Relationship values always generating links, regardless of target visibility

### ISSUE THREAD

**Issue by bfavaretto** [tainacan/tainacan#514]
**Bug description**

The HTML output for values of type Relationship is always a link pointing to the related Item. However, if the target item is not public, that link will lead to a 404 page, unless the current user is logged in and has enough permissions to view private/draft items. I'm considering this a bug for that reason, but if this is by design I'd be interested in hearing the rationale behind it. If you agree this is a bug, I actually have a fix ready, and I can submit a pull request if you're interested.

**How to reproduce such bug**

1. Add a Relationship value to an item, pointing to a private Item.
2. Check the public output of the relationship source while not logged in to Wordpress
3. Click the link to the related item. This should take you to a 404 page.

**Expected behavior**

Relationship values which are not public would not be output as links, but as plain text instead.

**Additional context**

As I said above, I have a fix for this issue in my own Tainacan fork, and I can submit a pull request if you're interested.

**Comment by leogermani** [comment]
Nice catch.

I wonder if the correct behavior is to display the plain text though. Because the item is private and we would be exposing private information there - even if just the title... 

Options

* Hide the item
* Add a generic title such as "Private item"

What do you think?

**Comment by bfavaretto** [comment]
Your concern makes sense – although the title is already being exposed anyway, so changing that might be an unwanted behavior for some of users. I personally don't like the idea of a generic "Private item" title, as it conveys no useful information. In my point of view, the ideal solution would be a more fine-grained visibility control, on the value level, in addition to the link removal I suggested. That would allow users to choose wether to display a link, a plain-text value, or nothing at all. Do you happen to have such kind of visibility control planned for the future?

**Comment by mateuswetah** [comment]
Hi @bfavaretto. We are curious to see your pull request!

Discussing with our team, it seems that the easier and more appropriate solution would be to hide the link. But I understand your concern with adding more options to this. We do have plans to provide more display settings to each metadata type. To name a few:
- Render URL metadata as a button instead of a link;
- Render other information from the relationship item, instead of only the metadata used to bound them;
- Render the image of taxonomy terms in the taxonomy metadata;

While it is not on top of our priorities list we certainly would love to discuss them.

Feel free to open the pull request, so we can discuss the implementation ;)

**Comment by bfavaretto** [comment]
Okay @mateuswetah, PR #515 submitted!

The changes I propose there are very basic, I just added a conditional on `post_status` around the code that generates the link.

You mentioned your plan for new metadata type options, are you suggesting to make that an option too? I mean, the admins would choose if they want to hide the values, or display them as plain text. That would work for me too! However, it's beyond what my current knowleged of Tainacan's internals allow me to implement by myself :(

Finally, thanks for the awesome and fast feedback! And congratulations for your work, Tainacan is a great tool!

**Comment by mateuswetah** [comment]
We forgot to close this, the pull request was approved and released in `0.18`.

It is worth mention that we are making some improvements on the display of metadata of the related item. The issue #572 should be done by next small release, allowing some metadata to be displayed in the metadata value, besides the one selected as search.
