### ISSUE TITLE
Missing PDF file when creating new Items

### ISSUE THREAD

**Issue by lb-ov** [tainacan/tainacan#554]
Hi,

**Bug description**
Prefix "\_x\_" concatenated to filename of "public" items.

What is happening? 
We have an installation of Tainacan 0.17.4 with 2000+ items and everything was working fine.  Since some days ago, we are getting an error message when creating a new Items:

Missing PDF file
PDF.js v1.9.426 (build: 2558a58d)
Message: Missing PDF "http://localhost/test/wp-content/uploads/tainacan-items/5/29760/art1.pdf".

The error raise after select the PDF file in the create new Item form.  It appears in the PDF view placeholder, in the "Document" field.

![imagen](https://user-images.githubusercontent.com/53535673/120050734-3867c580-bfdb-11eb-8933-41a4ead99ba1.png)

At the server side, I notice the file is uploaded in tainancan-items folder with "\_x\_" prefix, even when the Items were created "public".  Thumbnails were created correctly.

tainacan-items/5/_x_29760/art_1.pdf
tainacan-items/5/_x_29760/art_1.pdf.jpg
tainacan-items/5/_x_29760/art_1.pdf-170x220.jpg
tainacan-items/5/_x_29760/art_1.pdf-232x300.jpg
tainacan-items/5/_x_29760/art_1.pdf-791x1024.jpg

**How to reproduce such bug**
I installed a fresh wordpress 5.2.7 on my local computer with only a fresh installation of tainacan plugin, then I create a collection and tried to create an item, and I got the same error message:
Missing PDF file...

I tried editing the item, switching between "public" and "private" and "private" to "public" but nothing changed.  I keep getting the same error message.

**Expected behavior**
PDF file uploaded as public instead private

What did you expect to happen?
Not using prefix "\_x\_" In the tainacan-items forlder for public items

**Desktop (please complete the following information):**

 - OS: Ubuntu 18
 - Browser: Chrome
 - Version 88.0.1 

Could it be related to the wordpress versión 5.7.2?   Some clues about it?

**Comment by lb-ov** [comment]
Hello, I tried to find what could be the reason for this situation, but with no success yet. IMHO it could be related with the treatment of the post status. In the meantime I made a little change in the function get_document_as_html in .../plugins/tainacan/classes/entities/class-tainacan-item.php and it seems to be working now:

Add prefix "_x_" to the url if post status is not "publish"

![imagen](https://user-images.githubusercontent.com/53535673/122472955-758dfa80-cf7e-11eb-9c05-c625d5adb450.png)

I would appreciate if you could tell me if you consider this change is harmless or if it could have adverse effects?

Thanks.

**Comment by vnmedeiros** [comment]
Hi @lb-ov 

the `_x_` prefix by default indicates that the documents are part of a collection or a private item ([about File privacy](https://tainacan.github.io/tainacan-wiki/#/dev/private-files)).
The direct url access for items tagged with `_x_` should be denied to garante privacy of documents: https://tainacan.github.io/tainacan-wiki/#/dev/private-files?id=protecting-folders.

This change of yours works because you are directly accessing the URL, but if the ban rules are added to your server I think this should stop working.

Tainacan should change the physical address of the file (adding the prefix `_x_`) when an item is "non-public", in this part of the source code:
https://github.com/tainacan/tainacan/blob/daa95542015a2129a1cef551462b3c3a5cd91794/src/classes/class-tainacan-private-files.php#L170

I still can't reproduce this behavior here :confused:

**Comment by lb-ov** [comment]
Hello @vnmedeiros, thanks for your reply. Just for clarification, the problem is in the back-end, not in front-end. 

If I'm in the back-end with the administrator role I would expect that the PDF load in the PDF viewer iframe/placeholder even if it is private.

The behavior what I'm observing is that in the process of new Item creation, just after I load and select the PDF for the item and before I publish it, just in that moment, the iframe/placeholder that shows the PDF give me the error "Missing PDF...". The error tells can't find the PDF and shows the URL of the file, which does not have "\_x\_" prefix.  If I check the file system in that specific moment, I can see the "\_x\_" prefix in the file.   The PDF viewer is receiving the URL without "\_x\_" prefix, but file in filesystem have the "\_x\_".

IMHO, the URL should in that specific moment should have the "\_x\_" prefix because the "post" is in "auto-draft" status and it means the user hasn't saved it as public or private yet, and should not be available yet for external users, but the PDF visor in the back-end is receiving the URL without the "\_x\_" prefix, as if it was already published. 

What I did to workaround of this situation is put back again de "\_x\_" prefix to the URL if the post is not marked as "publish" and it seems to be working, even with the .htaccess rules.  I tested creating new items, switching items from public to private and other way round, return to draft and publishing again, and the PDF view is loading right, both back-end and front-end, the the "PDF Missing ..." error message is gone.

I  would want to think this change isn't harmless because it doesn't touch nothing in the database or filesystem, is a change just in the output, but I'm not sure...

**Comment by vnmedeiros** [comment]
Hi @lb-ov, sorry delay
I get to reproduce something similar here.
In my scenario, it is an error in the configuration of the `.htaccess` file, which was not redirecting 404 errors correctly.
you can take a test please, when trying to access the address, for example:
"http://localhost/test/wp-content/uploads/tainacan-items/fake404error". Are you redirected to the 404 page template (see figure) or just land on a "Not Found" page on the server? 

![dd](https://user-images.githubusercontent.com/1179250/124986728-541aae80-e012-11eb-87d5-6863fc2dd016.png)

**Comment by lb-ov** [comment]
Hi @vnmedeiros,

I did the test, the browser shows is "Not Found" 

![imagen](https://user-images.githubusercontent.com/53535673/125978371-783e2312-87cf-40dc-982a-4fa46330498f.png)

**Comment by vnmedeiros** [comment]
Hi @lb-ov,
It is very probably that there is a wrong redirect setting in one of your folders (wp-content, uploads or tainacan-items), look for the `.htaccess` file inside on folders, if you are using apache2 server, and correct the redirect/rewrite setting.

I think that fixing the redirecting page 404 also resolve problem with accessing the private files inside the folders marked with the `_ x_` prefix should be solved.
