### ISSUE TITLE
Error validating inherited metadata

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#57]
Something goes wrong when you have a required metadata in repository level and another required metadata in the collection and you try to publish the item with all fields blank.

If you fill the required metadata in the collection level, the validation of the metadata i the repository level works fine, but if you leave it blank, it breaks.

At first I thought it was something on the server side, but its not.

to reproduce:
. create a metadata at repository level and make it required
. create a metadata at collection level and make it required
. add new item
. click save leaving all fields blank

**Comment by mateuswetah** [comment]
I can't find the reason yet, but just to add here... You don't even need to hit the save button. If you onBlur one of the empty metadata, then try to do the same with the other, it's requests freezes everything. That's really serious...

**Comment by mateuswetah** [comment]
Just to clarify, this is not related to being a repository level field or not. In fact,with any two required metadata, after the onBlur of the second empty, the loop will happen.
