### ISSUE TITLE
Open ITEM page in the same browser tab

### ISSUE THREAD

**Issue by vserbu** [tainacan/tainacan#588]
**Context and motivation**

Why do you think this feature is needed? Who would benefit from it?

Everybody. Every time we click on ITEM, it's page is opened in separate tab. It confuses people, I think it would be beneficial if we can choose if it is going to open in the same tab or separate browser tab. 

**Ideal solution**

What would you describe as the best solution to implement such feature?

The best solution would be that we can choose between two options - open ITEM in new tab or in the same tab. 

**Alternative solutions**

Is there any other way to implement it?

I can not see one. 

**Additional context**

No.

**Comment by mateuswetah** [comment]
Hey @vserbu thank you for opening the issue here. We'll add it to our Todo list. For the Gutenberg blocks, it should be as simple as creating a new option. For the theme items list, maybe we should add an option to the Collection form or to a future repository level page (#438).

**Comment by mateuswetah** [comment]
Hey @vserbu, I'm thinking on getting this one for the next release, but will implement it gradually. Which is the context that you are expecting the most? I would start by the items Gutenberg blocks, we have around 5 that display items, but not sure if it is priority.

**Comment by vserbu** [comment]
Hi Mateus,

It would be great if it could be implemented into the next release, but I'm
not sure what you mean when talking about context. For me, it is pretty
straight forward, I'm not sure why it is not implemented by default,
because, when opening an item, it is logical to be open in the same tab,
instead, the browser could be pretty fast clogged with new tabs. Can you be
more specific? For the most part, I'm using Tainacan Items list, so maybe
you can start it from there. I'm not sure If someone considers opening in a
new tab as a useful feature, so can you add an option to choose - opening
in a new tab or opening in the same tab, or it must be implemented in some
other way?

best regards

Vedran

**Comment by mateuswetah** [comment]
I see your point there!

My question is more of, where should I start, because there are really a lots of places to create this option. You say that you are using _the Items list_. Just to be sure, is it the block itself? Because there is an item list in the theme pages and also, more than one block that displays items list:

![image](https://user-images.githubusercontent.com/1184874/132516685-9530b208-428a-4563-90dc-01c068387802.png)

**Comment by vserbu** [comment]
I see.

Maybe the best place where you can put it  is at the right sidebar where we
can change other preferences about that block. I'm attaching the image, so
you can create one more toggle on/off switch with the option "Open item in
the new tab". I'm sorry the sidebar image is partly in Croatian, but I
think you'll understand the context.

[image: sidebar.jpg]

**Comment by mateuswetah** [comment]
After a brief discussion with our support team, we decided to change the default behavior to open in the current tab. We found it to be more intuitive than the current behavior and possibly something that would add complexity to the gutenberg options if offered as an option. So if anyone still wants to have this customizable, feel free to open a new issue, but I believe version 0.18.6 will already please @vserbu needs.

**Comment by vserbu** [comment]
Thank you so much! Perfect! :)
