### ISSUE TITLE
Not exist the method set id in Item entity

### ISSUE THREAD

**Issue by rlima-ferreira** [tainacan/tainacan#613]
The method set_id no exist at class Item inside folder entity, beyond the method set_modification_date too not exist at class Item

**Comment by mateuswetah** [comment]
I believe this was handled a few years ago, but in any case, errors related to the documentation should be opened in the Wiki repository: https://github.com/tainacan/tainacan-wiki

And the live documentation is here: https://wiki.tainacan.org
