### ISSUE TITLE
Localizing strings with (missing) variables

### ISSUE THREAD

**Issue by pappasadrian** [tainacan/tainacan#642]
**Bug description**

Some strings are passed without their variables towards localization. 
For example: "2 items found" only passes "items found" via the info_items_found variable to tainacan-i18n.php
It would be more flexible for localization, to have such variables in the string, in order to choose the best syntax. In the above example in greek, it is best translated as "βρέθηκαν 2 αντικείμενα". 
Most strings are already handled like this with a %s variable but some have slipped through

This is not a serious bug that needs to be addressed ASAP, but it'd be a nice thing to have :)

**Additional context**

Variables where I have spotted this problem:
info_item_found
info_items_found
info_applied_filter
info_applied_filters

**Comment by mateuswetah** [comment]
Good catch @pappasadrian, we'll take a look at them next week, should be easy to fix. If you spot any other case, feel free to update this issue :)
