### ISSUE TITLE
Misspelling - Metadata edit & multiple other places

### ISSUE THREAD

**Issue by acesynapse** [tainacan/tainacan#731]
**Bug description**

Misspelling within metadata selections & several other places

**How to reproduce such bug**

Within Collection Metadata, open any edit window. "Description **bellow** name" 

**Expected behavior**

Should be spelled **below**

**Additional context**

Misspelling occurs:

tainacan-develop\src\classes\entities\class-tainacan-item.php - lines 626, 1068
tainacan-develop\src\classes\entities\class-tainacan-metadata-section.php - lines 21, 74, 78, 79, 134, 136, 139, 140
tainacan-develop\src\classes\entities\class-tainacan-metadatum.php - lines 17, 118, 122, 123, 325, 327, 330, 331
tainacan-develop\src\classes\repositories\class-tainacan-collections.php - line 252
tainacan-develop\src\classes\repositories\class-tainacan-metadata-sections.php - lines 65, 67, 69, 70, 149, 154, 160, 333
tainacan-develop\src\classes\repositories\class-tainacan-metadata.php - lines 91, 96, 98, 100, 101
tainacan-develop\src\classes\theme-helper\class-tainacan-theme-helper.php - lines 392, 1212
tainacan-develop\src\classes\theme-helper\template-tags.php - line 1129
tainacan-develop\src\views\admin\components\edition\item-edition-form.vue - line 415
tainacan-develop\src\views\admin\components\edition\metadata-section-edition-form.vue - lines 68, 69, 70, 74, 75, 78, 80, 81, 239
tainacan-develop\src\views\admin\components\edition\metadatum-edition-form.vue - lines 75, 76, 77, 81, 82, 85, 87, 88, 480
tainacan-develop\src\views\admin\components\metadata-types\tainacan-form-item.vue - lines 38, 40, 54, 55, 124, 125
tainacan-develop\src\views\gutenberg-blocks\blocks\item-submission-form\block.json - line 139
tainacan-develop\src\views\gutenberg-blocks\blocks\item-submission-form\deprecated.js - lines 132, 180, 227, 359, 399, 438, 570, 610, 648, 653
tainacan-develop\src\views\gutenberg-blocks\blocks\item-submission-form\edit.js - lines 57, 366, 367, 369, 370, 581, 582, 612, 612, 640, 641, 658, 659
tainacan-develop\src\views\gutenberg-blocks\blocks\item-submission-form\item-submission\item-submission-form.vue - lines 35, 40, 213, 218, 369, 374, 444, 463, 670
tainacan-develop\src\views\gutenberg-blocks\blocks\item-submission-form\save.js - lines 33, 87
tainacan-develop\src\views\gutenberg-blocks\blocks\item-submission-form\theme.js - lines 163, 191, 192
tainacan-develop\src\views\gutenberg-blocks\blocks\item-submission-form\theme.vue - line 23

**Comment by mateuswetah** [comment]
Hey thank @acesynapse for such detailed report!

As you might know, we are from Brazil and sometimes our English knowledge falls short. I'm moving this as high priority so we can fix it in the next minor release. Feel free to comment any other similar issues that you find here!

**Comment by acesynapse** [comment]
No worries! I just happened to notice it. Have a great day!

**Comment by mateuswetah** [comment]
Done! Sadly, not all cases could be fixed as some are in variables names which could cause backwards compatibility issues. But overall, all strings that appear to the user shall be corrected for next release.

**Comment by acesynapse** [comment]
Awesome! Glad to have helped even a little.
