### ISSUE TITLE
Adding metadata is not refreshed after rename.

### ISSUE THREAD

**Issue by frdbr** [tainacan/tainacan#761]
**Bug description**
When adding a metadata item and changing its name for example it only refreshes in the interface after a page reload. 

What is happening?

https://user-images.githubusercontent.com/77309092/211927385-c0ba8566-467d-4096-b446-cd9dce2f4277.mp4

**How to reproduce such bug**
See video

**Expected behavior**

For the info to refresh after saving it.

**Comment by mateuswetah** [comment]
Hey @frdbr thank you for reporting this bug! This is a simple one to fix, I'll add it to our to-do so we can fix it as soon as possible.

**Comment by frdbr** [comment]
Cool, I'm doing a small project with Tainacan, so I'll be reporting any issues if I find them.

**Comment by mateuswetah** [comment]
Great! Make sure to bring any doubts to our online forum: https://tainacan.discourse.group/

**Comment by mateuswetah** [comment]
Hey @frdbr, I believe I solved it. You can wait for our next release, which shall happen in a couple of weeks or test it via this link:
https://drive.google.com/file/d/1CLgGcybse3r7NVa5PUbmQSzRiNkTZ-s0/view?usp=share_link

This version may also include a fix to the "duplicated" metadata behavior that you mentioned in #711.
