### ISSUE TITLE
Metadata duplication on son's collections

### ISSUE THREAD

**Issue by johanpdr** [tainacan/tainacan#79]
I was create a collection named "_Relatórios_", and changed the names of metadata "_Title_" and "_Descripton_" to "**_Nome do documento_**" and "_**Descrição**_". 
When i setup a new collection has son of "_Relatórios_", the metadata "Title" and "Description" are created again and the metadata "**_Nome do documento_**" and "**_Descrição_**" was there too. Is this a expected behavior? 😕 
![captura de tela 2018-07-09 as 17 17 23](https://user-images.githubusercontent.com/6567563/42473793-f85ad47e-839b-11e8-8153-0f8eef68f66f.png)

**Comment by Weryques** [comment]
That isn't a expected behaviour, so here is the solution. Can you validate?
