### ISSUE TITLE
PHP 8.x compatibility: create_function

### ISSUE THREAD

**Issue by mikethicke** [tainacan/tainacan#791]
**Bug description**

The plugin is not compatible with PHP 8.x because it calls create_function, which has been removed. See: https://www.php.net/manual/en/migration80.incompatible.php

PHP 7.x is [no longer supported](https://www.php.net/supported-versions.php). 

**How to reproduce such bug**

1. Install PHP 8.x
2. Activate the plugin

**Expected behavior**

It works.

**Additional context**

create_function is used in two places in class-tainacan-bulk-edit-process.php: lines [519](https://github.com/tainacan/tainacan/blob/7ce6b9b71133a42b78185bb394ca1944cc3e09d5/src/classes/generic-background-process/class-tainacan-bulk-edit-process.php#LL519C21-L519C21) and [541](https://github.com/tainacan/tainacan/blob/7ce6b9b71133a42b78185bb394ca1944cc3e09d5/src/classes/generic-background-process/class-tainacan-bulk-edit-process.php#L541).

I'm not sure if there are other php 8.x incompatibilities.

Also---the [Contribution guidelines](https://tainacan.github.io/tainacan-wiki/#/dev/CONTRIBUTING) don't say anything about making pull requests. I would be happy to make the changes myself and open a pull request if preferred.

**Comment by mateuswetah** [comment]
Hey @mikethicke!

Very sorry for the late answer. First of all, thank you for pointing out this issue. We do need to make some moves to offer a proper PHP 8 integration. 

I'll add more information to the contribution docs, but if you are willing to contribute, you can do it via pull requests, we'll take a look before approving!

**Comment by mateuswetah** [comment]
Just an extra note here, we don't plan to remove 7.x support do soon, but 5.6 it is certainly about time!

**Comment by vnmedeiros** [comment]
https://github.com/tainacan/tainacan/issues/608
