### ISSUE TITLE
Add metadata "Date" loading forever

### ISSUE THREAD

**Issue by johanpdr** [tainacan/tainacan#80]
I started to configure metadata of a new collection adding metadata type "text" normally. At the third time i changed idea and cancelled add metadata type "text", i deleted it and started to add a metadata type "Date". When i dropped to the left the box "date", a "loading" icon appeared on "date box" at right, and after this i cant get add others metadata anymore. 😢 
![captura de tela 2018-07-09 as 17 26 21](https://user-images.githubusercontent.com/6567563/42474840-2abadd3a-839f-11e8-8549-7e0e41789c74.png)

**Comment by Weryques** [comment]
We did not got reproduce that. So I'm closing that issue. If do you has more information about, you can reopen this issue.
