### ISSUE TITLE
avoid displaying private metadata fields on item page?

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#805]
hi, doing some Tainacan tweaks again, happy to see all the changes and improvements!

I'm thinking about private metadata fields (where status is set to "private") – at least in my case I want those to not be displayed on the item page.

I think the proper way to check if a metadatum is private should go here:
https://github.com/tainacan/tainacan/blob/5ef769915ea81349e0d13f49acd29a21667a6950/src/classes/entities/class-tainacan-item.php#L612C16-L612C16

…but I don't know how to check whether the metadatum is public or private.

**Comment by mateuswetah** [comment]
Hi @Ambrosiani!

Glad to have you here. Unfortunately, we couldn't make improvements in all the areas that we needed, but still, we have some big plans for the next year. 

Regarding private metadata. They are not rendered (or at least should not render) in the item page, unless you are logged in. If your user is logged in and it has privileged to read private metadata, then it will see them, even outside the admin area. But if you are a user with lesser permissions or aren't logged in, then they shouldn't be displayed at all.

**Comment by Ambrosiani** [comment]
of course I hadn't checked in logged out mode… nothing is rendered then, as it should be. I'll close this issue, and create a new one with a suggested improvement for those (like me) who didn't figure this out by themselves…
