### ISSUE TITLE
show status of public/private metadata on object pages for logged in users

### ISSUE THREAD

**Issue by Ambrosiani** [tainacan/tainacan#806]
**Context and motivation**

Public and private metadata fields are displayed in the same way for logged in users. For me this led to the confusion that I thought the private fields were displayed for everyone.

**Ideal solution**

Perhaps: add a lock icon (🔒) next to the metadata field title for private fields, similar to how they are displayed in the metadata tab in the Tainacan admin interface?

**Comment by mateuswetah** [comment]
I agree with the motivation, this confusion actually happens a lot for many users. 

The lock icon would be ideal, but I can't figure a way to make it generic sufficient in order that any theme would display it nicely. We would have to either add an SVG icon, an image or a font icon (which is the case inside the Tainacan Admin). That would probably require a css to be loaded to adjust it.

My proposal, which is not that pretty but should solve the problem, is to prepend _"Private:"_ or maybe append _"(private)"_ to the metadata label. This would be the same solution that WordPress already does to Item names when they are fully private.

**Comment by Ambrosiani** [comment]
sounds like a good fix!
