### ISSUE TITLE
Special fields for CSV Importer

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#86]
Implement special fields in CSV Importer. These fields will add values to the Item Document or attach files to the item.

## Special fields

These fields, declared in the CSV header, will be ignored for the mapping. 

These fields should start with "special_" 

So any field stating with this will be ignored in the mapping.

## Handling special fields

When importing the items, we will handle some of these fields in a special way:

1. special_document -> will add value to the item document

2. special_attachments -> will add attachments to the document

## Special fields values

The values of these fields must also be special.

For the document field, values have to be prepended with "url:", "file:" or "text:". This will indicate the document_type.

If the type is file, Tainacan will handle the file insertion. This could be done downloading a file from a URL or adding a file that is present on the server (which, for example, was uploaded via FTP).

So you can have:

- file:http://domain.com/image.jpg
- file:photos/image.jpg

In the case of attachments, you dont need to prepend the value with "file:", because they will allways be files, but you may have more than one file, separeted by the multiple value separator.

## Option for local folder

Finally we have to add one more option to the importer, which is the local path to the folder where the files are. So, in case the file is not an URL, but a relative path, this will be the base path.

We will have to find room in this options form to explain all that, but lets make it work first.

**Comment by eduardohumberto** [comment]
create thumbnail in document images
