### ISSUE TITLE
Elastic Search integration (via ElasticPress plugin)

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#90]

**Comment by leogermani** [comment]
Basic integration done only for fetching items

I had some bad results fetching for collections and metadata. There must be some problems with items as well. A lot of verification is still needed in order to use this.

Also, we must deal with actions that will require resync with the Elastic Search database. For example, bulk edit actions that bypass internal WordPress routines.

**Comment by vnmedeiros** [comment]
- [ ] Retornar facetas quando a requisição for feita para mais de uma coleção.
- [ ] Realizar busca sobre as facetas retornadas.
- [ ] Adicionar o paramentro `last_term` ao endpoint da faceta.
- [ ] O endpoint da faceta deve receber como paramentro o ID do filtro não o ID do metadado
- [ ] Adicionar ao retorno do endpoint da faceta os elementos passado no paramentro `include`
- [ ] Endpoint da faceta deve ter a mesma estrutura de retorno quando o plugin elasticpress estiver desativado.

**Comment by mateuswetah** [comment]
Latest commit begins integration with frontend. There are numerous checks that I'm listing here to keep better control on what we need to test:
- [ ] Plain text value static options (checkbox and select)
- [ ] Plain text value searchable options (autocomplete, taginput)
- [ ] Relationship values
- [ ] Same above for Taxonomy
- [ ] Checkboc Modal, for both text and taxonomy
- [ ] Other ocurrencies of `/items`,  such as exposers modal
- [ ] Check other sorting values than `creation_date`

**Comment by vnmedeiros** [comment]
- [ ] Add properties to activate and deactivate the `max-options` return in filters.
- [ ] Fix data return on request has the option `include` for metadata with multiples values.

**Comment by leogermani** [comment]
Back to our To do list to solve the last point:

To add a notification in the admin panel when there is the need for a resync. (for example, when there was a bulk edit process)

**Comment by vnmedeiros** [comment]
- [ ] fix error in indexing document content
> `array_filter() expects parameter 1 to be array, object given in /var/www/html/wp-content/plugins/tainacan/classes/class-tainacan-elastic-press.php on line 86`
