### ISSUE TITLE
Rearrange metadata forms

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#91]
Review and rearrange the order of the fileds in the metadata options forms.

I think the can be re-prioritized. And maybe hide some more advanced options in a collapse menu...

Also, there are some spacing that do not look right (between sectiontitles and radio options)

![captura de tela de 2018-07-29 13-36-06](https://user-images.githubusercontent.com/971483/43368537-20c67294-9335-11e8-870a-54e7c37b50dc.png)

**Comment by mateuswetah** [comment]
The design team proposed two-columns layout, which is now implemented. Labeling space on radio and checkbox list is fixed. The advanced options was considered a bit dubious, as this could vary from user interaction with that form. I believe the semantic URI is the only one really "extraneous" for most use cases we have today. According to their layout we have this to work on too: Ref. #173.
