### ISSUE TITLE
Metadata repository fetch method should accept no arguments

### ISSUE THREAD

**Issue by alantygel** [tainacan/tainacan#919]
Its not really a bug, but only a lack of consistency.

Collection, Items, Filters and other Repositories have a default empty array on fetch input (` function fetch( $args = [], ...`). Metadata should also have one.

Reference: https://github.com/tainacan/tainacan/blob/cdddca3e6ba7dd5acc62b39d9c7aebd36a52d269/src/classes/repositories/class-tainacan-metadata.php#L347C30-L347C31

**Comment by thegamerjedbest45454** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by vnmedeiros** [comment]
resolved in PR: https://github.com/tainacan/tainacan/pull/918
