### ISSUE TITLE
Elements under Masonry or Records view are not displayed properly upon filters component expansion

### ISSUE THREAD

**Issue by smllb** [tainacan/tainacan#923]
**Bug description**
Elements under Masonry or Records view are not displayed properly upon filters component expansion.   
What is happening?
Once the filters are expanded, assuming they are closed in the first place, sometimes the items won't be recalculated and end compressed as a group within the available space, most of the time on top of each other.
**How to reproduce such bug**

1. Open the archive
2. Select Masonry or Records view
3. Hide the filters if they are open in the first place (most will be open by default in the faceted search)
4. Expand the filters

**Expected behavior**

Items in list being recalculated when other components come into play.

**Screenshots**

![Visual Example](https://i.imgur.com/Zsr85dC.gif)

**Live example**
[Museu Paulista - Acervo](https://acervoonline.mp.usp.br/iconografia/?perpage=12&view_mode=records&paged=1&order=ASC&orderby=date&fetch_only_meta=19%2C8%2C23%2C37%2C58%2C66&fetch_only=thumbnail)

**Desktop**

 - OS: Windows 10
 - Browser: Brave (happened in others too)
 - Version: Latest

**Additional context**

In our current project (fyi: not the given example above), we proposed a temporary workaround in JavaScript to retrigger a view selection once the filters are expanded, because the system knows how to calculate the distribution of items given a fixed width at the time of execution.
I suggest something similar, but just to recalculate the elements in the screen, bypassing the usual flow of doing the requests from the start.
Been happening in the last version of Tainacan available through Wordpress public search but i noticed that not all projects have this issue, so there's a chance of being theme incompatibilities of some sort.

**Comment by mateuswetah** [comment]
> In our current project (fyi: not the given example above), we proposed a temporary workaround in JavaScript to retrigger a view selection once the filters are expanded, because the system knows how to calculate the distribution of items given a fixed width at the time of execution.
I suggest something similar, but just to recalculate the elements in the screen, bypassing the usual flow of doing the requests from the start.

We do this:
https://github.com/tainacan/tainacan/blob/f3c7fce172f727e60306e64e2db433d88e907577/src/views/gutenberg-blocks/blocks/faceted-search/theme-search/components/view-mode-masonry.vue#L127-L133

But it seems that is not being enough... I need to investigate more because it is hard to reproduce but I do see it happening from time to time.

**Comment by mateuswetah** [comment]
Forgot to tag but this commit: https://github.com/tainacan/tainacan/commit/6dd1ddea3c44974f152b28b807d8d476f3cf2603

Seems to solve it. The issue was that we should first wait for the collapsing animation finish before reloading the masonry layout.
