### ISSUE TITLE
Endpoints to load facets

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#94]
Change the way we fetch facets.

Instead of fethcing values directly, lets create a specific endpoint to load faceted based on:

. the metadata to use as a filter
. the current query

internally we fetch for the possible values.

This will allow us to:

. add items count to the facet list
. display only values that have results
. override this endpoints with other approaches, such as elastic search

**Comment by eduardohumberto** [comment]
- [ ]  create unique endpoint to retrieve filter data
