### ISSUE TITLE
Admin interface plugin API

### ISSUE THREAD

**Issue by leogermani** [tainacan/tainacan#96]
Plan how to make the admin interface extensible via plugins: new menus, new inputs in forms, etc

**Comment by mateuswetah** [comment]
[Last commit](5627ce2bdebe...c8183b79ad19) merges from a branch where form hooks is implemented. This solves an important part of the issue. Next we might discuss how to deal with pages and menu items.

**Comment by leogermani** [comment]
We are now able to add stuff to forms:

item form
metadata form
filter form
collection form

Another issue will be opened to add the possibility to add new items to menus and new pages to the admin
